components/13-ironic/aio-values.yaml, docs/install-understack-ubuntu-k3s.md, mkdocs.yml
Adds a step by step guide to getting UnderStack up and running on a Ubuntu server with K3s.
=> feat: Adds tutorial/guide to installing UnderStack on Ubuntu and K3s

apps/components/argo-events.yaml, apps/components/argo-workflows.yaml, apps/components/dexidp.yaml, apps/components/ironic.yaml, apps/components/keystone.yaml, apps/components/mariadb.yaml, apps/components/memcached.yaml, apps/components/nautobot.yaml, apps/components/postgres-db.yaml, apps/components/rabbitmq-cluster.yaml, scripts/gitops-deploy.sh
Allow overriding the understack ref to a branch or a tag for use in the gitops workflow for testing purposes.
=> feat: allow overriding the understack ref to use in gitops

docs/gitops-install.md
=> fix: fix small typo

components/dexidp/values.tpl.yaml
Fixes bad config generated by #40
=> fix: dex staticClients must be under the config

apps/operators/ingress-nginx.yaml, scripts/gitops-deploy.sh
Create the helm-configs file for ingress-nginx to allow the user to configure the ingress.
=> feat: add helm-configs for ingress-nginx

apps/components/argo-workflows.yaml, apps/components/dexidp.yaml, apps/components/ironic.yaml, apps/components/keystone.yaml, apps/components/mariadb.yaml, apps/components/nautobot.yaml, apps/operators/cert-manager.yaml, apps/operators/ingress-nginx.yaml, apps/operators/mariadb-operator.yaml, apps/operators/messaging-topology-operator.yaml, apps/operators/postgres-operator.yaml, apps/operators/rabbitmq-operator.yaml, docs/gitops-install.md, scripts/gitops-deploy.sh
Allow the user to use a branch of their deploy repo for templating out the configs.
=> feat: allow user to use a branch of their deploy repo

components/keystone/aio-values.yaml
https://docs.openstack.org/keystone/latest/admin/federation/configure_federation.html
=> feat: Updates keystone configuration to allow oidc auth integration

README.md, bootstrap/metallb/README.md, bootstrap/metallb/example-app-with-lb.yaml, bootstrap/metallb/example-create-metallb.yaml, bootstrap/metallb/kustomization.yaml
Adds metallb: https://metallb.universe.tf/ along with a couple examples using it.
=> feat: adds metallb

apps/components/argo-workflows.yaml
Template out setting the argo workflows ingress hostname correctly
=> feat: template out argo workflows ingress hostname

scripts/easy-secrets-gen.sh, scripts/gitops-deploy.sh
fixed gitops-deploy on Bourne shell and make gitops-secrets idempotent
=> fix: fixed gitops-deploy on Bourne shell and make gitops-secrets idempotent

bootstrap/ingress-nginx/values.yaml, components/ironic/dnsmasq-cm.yaml, components/ironic/dnsmasq-ss.yaml, containers/dnsmasq/dnsmasq.conf.j2
Dropped all usage of hostPorts so we can always use load balancer IPs.
=> fix: drop usage of hostPorts

.github/workflows/containers.yaml, components/openstack-2024.1-jammy.yaml, containers/Dockerfile.ironic
Added OpenStack 2024.1 containers so we can deploy 2024.1
=> feat: add OpenStack 2024.1

.github/workflows/typos.yaml, .typos.toml
Adds Typos spell checker github action: https://github.com/crate-ci/typos
=> feat: Adds typos spell checker config and github action

docs/auth.md, docs/gitops-install.md
Linked the auth doc from the gitops page and added some information about configuring authorization.
=> docs: add authorization information to docs

components/ironic/aio-values.yaml, components/ironic/values.tpl.yaml
Set the default interfaces we want to use for running our Ironic.
=> feat: setup default values for Ironic

.github/workflows/build-container-images.yaml, argo-workflows/generic/code/argo_python/README.md, argo-workflows/generic/code/argo_python/__init__.py, argo-workflows/generic/containers/Dockerfile.argo_utils, argo-workflows/generic/deps/placeholder-obm-creds-secret.yaml, argo-workflows/generic/docs/README.md, argo-workflows/generic/workflowtemplates/get-device-nautobot.yaml, argo-workflows/generic/workflowtemplates/get-obm-creds.yaml, argo-workflows/generic/workflowtemplates/get-obm-ip.yaml, argo-workflows/generic/workflowtemplates/nautobot-api.yaml, argo-workflows/obm-utils/code/obm_firmware_update.py, argo-workflows/obm-utils/code/obm_sync_creds.py, argo-workflows/obm-utils/containers/Dockerfile.obm_utils, argo-workflows/obm-utils/containers/requirements.txt, argo-workflows/obm-utils/deps/placeholder-obm-legacy-passwords-secret.yaml, argo-workflows/obm-utils/docs/README.md, argo-workflows/obm-utils/workflowtemplates/obm-firmware-update.yaml, argo-workflows/obm-utils/workflowtemplates/obm-sync-creds.yaml, components/argo-events/argo-role.yaml, components/argo-workflows/kustomization.yaml
This adds some common generic workflow templates, bumps argo-workflows to 2.5.6, as well as adjust the argo-role to allow for http template usage as well as memoization.
=> feat: adds some common argo-workflows workflow templates

.pre-commit-config.yaml, argo-workflows/generic/docs/README.md, argo-workflows/generic/workflowtemplates/get-obm-creds.yaml, argo-workflows/obm-utils/docs/README.md, docs/component-argo-events.md, docs/component-argo-workflows.md, docs/component-overview.md, mkdocs.yml
Initial workflow and events docs, as well as some pre-commit linting.
=> docs: argo workflow and events docs

components/ironic/dnsmasq-cm.yaml, containers/Dockerfile.dnsmasq, containers/dnsmasq/dhcp-allowed-srvids.patch, containers/dnsmasq/dnsmasq.conf.j2, docs/networking.md
Added the ability to manage multiple ranges and options in dnsmasq by defining multiple environment variables.
=> feat: add multiple options and ranges to dnsmasq

containers/dnsmasq/dnsmasq.conf.j2
=> fix: dnsmasq- render for PROVISIONER_INTERFACE

apps/components/argo-workflows-templates.yaml
Adding our argo-workflows and dependency manifests as an Argo CD Application.
=> feat: add argo workflow templates to argo cd application automation

docs/gitops-install.md, scripts/easy-secrets-gen.sh, scripts/gitops-secrets-gen.sh
- argocd Application 'sources' correctly reads 'kind: SealedSecret' and creates Secrets
- will prevent committing bare secrets to git
=> feat: incorporate sealed secrets into gen scripts

apps/components/neutron.yaml, components/neutron/README.md, components/neutron/aio-values.yaml, components/neutron/kustomization.yaml, components/neutron/neutron-mariadb-db.yaml, components/neutron/neutron-rabbitmq-queue.yaml, components/neutron/values.tpl.yaml, scripts/easy-secrets-gen.sh
Adds initial setup of openstack neutron.
=> feat: Adds OpenStack Neutron base install to UnderStack

docs/overrides/home.html, docs/vision.md, mkdocs.yml
Attempt to explain the vision of Understack at a high-level.
=> docs: add initial vision

.pre-commit-config.yaml
Let's spellcheck when people commit
=> chore: add typos to pre-commit

containers/dnsmasq/dnsmasq.conf.j2
Added some debugging and check that values are truthy before using them in the jinja template for dnsmasq.
=> chore: add some more jinja details for dnsmasq

apps/appsets/openstack/openstack.yaml, components/neutron/aio-values.yaml, components/nova/aio-values.yaml, components/openstack-2023.1-jammy.yaml, components/openstack-2024.1-jammy.yaml, components/openstack-secrets.tpl.yaml, components/placement/README.md, components/placement/aio-values.yaml, components/placement/kustomization.yaml, components/placement/placement-mariadb-db.yaml, components/placement/values.tpl.yaml, scripts/gitops-deploy.sh, scripts/gitops-secrets-gen.sh
Attempt to fix the templating to be able to successfully deploy Neutron and Nova. Added Placement since it seemed to be required by Nova.
=> fix: deployment of OpenStack Neutron and Nova

apps/appsets/workflows.yaml, apps/kustomization.yaml
This is a specific, and hopefully temporary, AppSet to deploy the workflows.
=> feat: add AppSet for workflow deployment

components/argo-events/argo-rabbitmq.yaml, components/argo-events/kustomization.yaml, components/argo-events/openstack-event-source.yaml, scripts/gitops-secrets-gen.sh
This EventSource provides events generated by the in-cluster Ironic instance and can be consumed to react to changes happening there.
=> feat: AMQP / Ironic event source

.github/workflows/containers.yaml
=> fix: neutron image prefix

apps/appsets/openstack.yaml, components/glance/aio-values.yaml, components/glance/glance-mariadb-db.yaml, components/glance/glance-rabbitmq-queue.yaml, components/glance/kustomization.yaml, components/glance/values.tpl.yaml, components/openstack-secrets.tpl.yaml, scripts/gitops-deploy.sh, scripts/gitops-secrets-gen.sh
Deploy a very minimal OpenStack Glance that's just using a PersistentVolumeClaim for now. In the future we can configure other storage backends.
=> feat: add OpenStack Glance to be deployed

components/undersync/service.yaml
=> fix: Update undersync service definition to match the actual container port

components/ironic/aio-values.yaml
A couple small adjustments to the ironic configuration.
=> feat: Ironic configuration tuning

.github/workflows/code-test.yaml, .gitignore, python/understack-workflows/poetry.lock, python/understack-workflows/pyproject.toml
Run coverage automatically when running pytest
=> chore: add running of coverage on pytest

argo-workflows/trigger-undersync/workflowtemplates/undersync-device.yaml
=> fix: undersync-device: fix argument name

.markdownlint.yml, docs/kubernetes.md, docs/user-guide/openstack-cli.md
Fixed the code block style and add rules to avoid breaking checks in the future.
=> docs: fix code block style

apps/appsets/components.yaml
87fbe9bd didn't include nautobot secrets
=> fix: 87fbe9bd didn't include nautobot secrets

apps/appsets/components.yaml, components/dex/ingress.yaml
The hostname is incorrect and the default ingressClassName wasn't set.
=> fix: fix incorrect settings for dex ingress

docs/user-guide/rabbitmq-cheat-sheet.md, mkdocs.yml
=> docs: adds rabbitmq cheat sheet

apps/app-of-apps.yaml, apps/appsets/argocd.yaml, docs/deploy-guide/gitops-install.md, scripts/gitops-secrets-gen.sh
Added the ability for one ArgoCD to manage multiple clusters and deployments.
=> feat: allow one ArgoCD to manage multiple clusters

apps/appsets/argocd-operators-project.yaml, components/nautobot/cloudnative-postgres-nautobot.yaml, components/nautobot/kustomization.yaml, components/nautobot/nautobot-values.yaml, docs/user-guide/postgres-operator-cheat-sheet.md, mkdocs.yml, operators/cnpg-system/README.md, operators/cnpg-system/kustomization.yaml
Adds the CloudNativePG postgres operator: https://cloudnative-pg.io/
=> feat: adds cloudnative-postgres operator

.github/workflows/mkdocs.yaml, Makefile, scripts/argo-workflows-to-mkdocs.py
Restored the ability to use the makefile to build the docs locally. Make the CI use the makefile as well to preserve the functionality in the future.
=> fix: restore ability to use makefile to build docs locally

.github/workflows/yamllint.yaml, scripts/gitops-secrets-gen.sh
Fixed some shell issues identified by shellcheck and add running shellcheck to avoid issues in the future.
=> fix(gitops-secrets-gen): fix some shell issues and add a test

.github/workflows/containers.yaml, containers/Dockerfile.dnsmasq, containers/Dockerfile.ironic-nautobot-client
Make it possible to test our containers by building and pushing the containers for the life of the PR. Once the PR is closed we'll delete and clean up the containers.
=> ci: build and clean up containers on each PR

apps/appsets/components.yaml, apps/appsets/infra.yaml, apps/appsets/openstack.yaml, docs/deploy-guide/add-remove-app.md, mkdocs.yml
Added some basic info on how to add, remove and modify our ArgoCD deployed applications. Made some tweaks to make them behave more consistent.
=> docs: add/remove/modify ArgoCD deployed applications

docs/user-guide/mariadb-operator-cheat-sheet.md, mkdocs.yml
Adds my notes for connecting to the mariadb-operator's databases from my local machine.
=> docs: Adds mariadb operator cheat sheet

components/keystone/aio-values.yaml
Added the email to the user and made it possible to update the mapping. Remove duplicate creation of groups.
=> feat: update keystone mapping

apps/appsets/components.yaml
These files are created in https://github.com/RSS-Engineering/undercloud-deploy/pull/144
=> feat: Update understack-workflows sources to pull in undercloud-deploy too

components/keystone/aio-values.yaml, operators/rabbitmq-system/cluster-operator/kustomization.yaml, operators/rabbitmq-system/kustomization.yaml, operators/rabbitmq-system/messaging-topology/kustomization.yaml, python/neutron-understack/neutron_understack/tests/conftest.py, python/neutron-understack/neutron_understack/tests/test_neutron_understack_mech.py, python/neutron-understack/pyproject.toml, scripts/gitops-secrets-gen.sh
When creating a new environment these are some issues that @skrobul stumbled over.
=> fix: deployment issues identified when creating a new env

containers/argo_utils/README.md, containers/argo_utils/code/argo_python/__init__.py, containers/obm-utils/README.md, docs/component-argo-workflows.md, workflows/argo-events/sensors/nb-oob-interface-update.yaml, workflows/argo-events/workflowtemplates/get-device-nautobot.yaml, workflows/argo-events/workflowtemplates/get-obm-creds.yaml, workflows/argo-events/workflowtemplates/get-obm-ip.yaml, workflows/argo-events/workflowtemplates/idrac-enable-network-boot.yaml, workflows/argo-events/workflowtemplates/obm-firmware-update.yaml, workflows/argo-events/workflowtemplates/obm-sync-creds.yaml, workflows/argo-events/workflowtemplates/sync-nb-server-to-ironic.yaml, workflows/argo-events/workflowtemplates/sync-obm-creds.yaml, workflows/argo-events/workflowtemplates/sync-srv-redfish-intfs-to-nb.yaml
closes PUC-504
(I need to re-open this PR because CI won't I on a fork)
=> Update workflows to identify devices by id instead of hostname

apps/appsets/components.yaml, components/chrony/deployment.yaml, components/chrony/kustomization.yaml, components/chrony/service.yaml
This is needed for NTP sync when the servers are deployed (IPA stage)
=> feat: add chrony component

python/understack-workflows/understack_workflows/main/undersync_device.py
So that it is somewhat more readable.
=> chore: pretty print undersync's response

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, components/nautobot/dexauth.py, components/nautobot/nautobot_config.py, containers/argo_utils/code/argo_python/__init__.py, containers/bmc-utils/code/bmc_firmware_update.py, containers/bmc-utils/code/bmc_sync_creds.py, python/ironic-understack/ironic_understack/conf.py, python/ironic-understack/ironic_understack/flavor_spec.py, python/ironic-understack/ironic_understack/machine.py, python/ironic-understack/ironic_understack/redfish_inspect_understack.py, python/ironic-understack/ironic_understack/tests/test_flavor_spec.py, python/ironic-understack/ironic_understack/tests/test_machine.py, python/ironic-understack/ironic_understack/tests/test_matcher.py, python/neutron-understack/neutron_understack/argo/workflows.py, python/understack-workflows/tests/conftest.py, python/understack-workflows/tests/test_sync_bmc_creds.py, python/understack-workflows/tests/test_sync_nautobot_system_info.py, python/understack-workflows/tests/test_sync_server.py, python/understack-workflows/understack_workflows/main/undersync_device.py, python/understack-workflows/understack_workflows/models.py, python/understack-workflows/understack_workflows/nautobot.py, python/understack-workflows/understack_workflows/port_configuration.py, python/understack-workflows/understack_workflows/undersync/client.py, scripts/argo-workflows-to-mkdocs.py
Enables using pre-commit in CI to keep things checked on PRs.
=> ci: enable pre-commit on the repo

components/keystone/aio-values.yaml, components/nova/aio-values.yaml, components/openstack/svc-acct-argoworkflow.yaml, workflows/argo-events/secrets/openstack-svc-acct.yaml
Move the project that our servers live in and get controlled in do a new domain called 'infra' with a project called 'baremetal'
=> chore: migrate nodes to live in baremetal project

.pre-commit-config.yaml, .typos.toml, schema/README.md, schema/argo-workflows.json
Don't pull it down every single time since it can fail and you might not be connected to the internet.
=> chore: vendor the argo-workflows jsonschema

components/ironic/aio-values.yaml
https://docs.openstack.org/ironic/latest/admin/drivers/redfish/metrics.html
=> feat(ironic): enable sensors for redfish metrics

workflows/argo-events/eventbus/eventbus-default.yaml, workflows/argo-events/eventbus/poddisruptionbudget-eventbus-default-pdb.yaml
2a03582d57dc incorrectly deleted these files instead of moved them to the new location.
=> fix(workflows): add back incorrectly deleted files

.github/workflows/typos.yaml
Avoid getting broken by pinning a version
=> ci: pin a typos version to not break

.github/workflows/containers.yaml, apps/appsets/openstack.yaml, components/openstack-2024.2-jammy.yaml
Ensure we build our containers for OpenStack 2024.2 and create a values file referencing the 2024.2 container releases.
=> feat: prep for upgrade to OpenStack 2024.2

apps/appsets/openstack.yaml
=> feat: switch to OpenStack 2024.2

docs/user-guide/openstack-ironic.md, docs/user-guide/openstack-placement.md, mkdocs.yml
Notes and docs on using various openstack tools
=> docs: adds additional openstack docs

components/ironic/aio-values.yaml
Automated node cleaning works fine in my tests. 👍
=> feat(ironic): enable automated cleaning of nodes

python/understack-workflows/understack_workflows/port_configuration.py, python/understack-workflows/understack_workflows/sync_interfaces.py
Openstack wants this field to have data in it
=> feat: populate Ironic baremetal port `local link connection` field on server enroll

components/ironic/aio-values.yaml
https://docs.openstack.org/ironic/latest/admin/cleaning.html#storage-cleaning-options
=> feat(ironic): use express disk cleaning operations

python/understack-workflows/understack_workflows/main/undersync_device.py
API endpoint url changed in https://github.com/RSS-Engineering/undercloud-rackspace/pull/254/files
=> fix: fix prep_switch_interface url

python/neutron-understack/neutron_understack/nautobot.py, python/neutron-understack/neutron_understack/neutron_understack_mech.py
When  `openstack network delete` is issued, delete network in NB
=> feat: delete tenant network

docs/deploy-guide/index.md
Add some more information around how we expect the system to be deployed using the deployment guide.
=> docs: describe how we expect the system to be deployed

python/understack-workflows/understack_workflows/sync_interfaces.py
Having the correct data to hand will simplify later nautobot jobs.
=> chore: Change the value that Enroll workflow sets in Ironic local_link_info

python/understack-workflows/understack_workflows/main/sync_keystone.py
When updating a tenant that doesn't exist in Nautobot, just create it instead to get it in sync.
=> fix(workflows): create tenant in nautobot if it doesn't exist

.gitignore, docs/component-understack-workflows.md, scripts/argo-workflows-to-mkdocs.py
=> fix: updates argo to mermaid script for new workflow directory structure and layout

.github/workflows/lint-workflow-templates.yaml
Add git workflow to argo lint understack workflow templates.
=> feat: lint workflow templates

docs/user-guide/rook-ceph.md, mkdocs.yml
=> docs: adds docs for ceph

examples/tf-multi-node-build/.gitignore, examples/tf-multi-node-build/README.md, examples/tf-multi-node-build/main.tf, examples/tf-multi-node-build/variables.tf, examples/tf-multi-node-build/versions.tf
Provide a very basic example of building machines via terraform.
=> feat: add an example of building machine via terraform

docs/user-guide/openstack-cli.md
How to create and use application credentials
=> docs: Adds application credential documentation

scripts/README.md, scripts/nautobot_graphql_queries/get_hosts_in_rack.gql, scripts/nbgql.sh, scripts/rekick-rack.sh
Adds a couple infrastructure administration scripts:
* nbgql.sh - query nautobot's graphql. useful for piping the output to other scripts
* rekick-rack.sh - uses nbgql.sh to find servers in a rack and rekicks them
=> feat: adds some infrastructure management scripts

workflows/openstack/sensors/sensor-neutron-deployment.yaml
=> fix: fix lint-yaml warning

python/understack-workflows/tests/json_samples/bmc_chassis_info/R7615/_redfish_v1_Managers_iDRAC.Embedded.1_Oem_Dell_DellAttributes_iDRAC.Embedded.1.json, python/understack-workflows/tests/json_samples/bmc_chassis_info/R7615/_redfish_v1_Systems_System.Embedded.1_NetworkPorts_Oem_Dell_DellSwitchConnections_.json, python/understack-workflows/tests/test_bmc_chassis_info.py, python/understack-workflows/tests/test_nautobot_device.py, python/understack-workflows/understack_workflows/bmc_chassis_info.py
=> fix: Enroll was failing because of MAC addresses printed without leading zeros by Dell

apps/appsets/openstack.yaml, components/neutron/aio-values.yaml, components/openstack-2024.2-jammy.yaml, components/openvswitch/aio-values.yaml, components/ovn/aio-values.yaml, docs/operator-guide/debug-ovs-ovn.md, mkdocs.yml
Added a deployment of OVS and OVN so that we can utilize OVN for Neutron L3 routing.
=> feat: add OVN for Neutron L3 routing

docs/user-guide/openstack-cli.md, examples/tf-multi-node-build/README.md
Create a scriptable command to make the app creds.
=> docs: make app cred generation scriptable

python/understack-workflows/tests/test_sync_keystone.py, python/understack-workflows/understack_workflows/main/sync_keystone.py
Added some more checks to the keystone sync so that its called by the python wrapper correctly to exit with a non-0 code when it fails. Added more debug logging so we can see what went wrong in more cases.
=> fix(workflows): add more checks and logging to keystone sync

python/understack-workflows/understack_workflows/main/sync_keystone.py
Log the existing tenant, if we find one.
=> chore: add additional logging to help troubleshoot

docs/operator-guide/openstack-ironic.md
Adds docs for troubleshooting ironic bare metal nodes.
=> docs(ironic): adds ironic node troubleshooting documentation

python/understack-workflows/tests/fixture_nautobot_device.py, python/understack-workflows/tests/json_samples/bmc_chassis_info/R7615/nautobot_graphql_response_server_device_33GSW04.json, python/understack-workflows/tests/json_samples/nautobot_device_data.json, python/understack-workflows/understack_workflows/nautobot_device.py, python/understack-workflows/understack_workflows/port_configuration.py, python/understack-workflows/understack_workflows/sync_interfaces.py
closes PUC729
requires https://github.com/RSS-Engineering/undercloud-rackspace/pull/329
=> feat: Have Enroll set physical network when creating ironic baremetal ports

docs/operator-guide/workflows.md, mkdocs.yml
Adds an operator guide for Argo Workflows and how to troubleshoot them.
=> docs(workflows): adds operator docs for argo workflows

python/ironic-understack/ironic_understack/redfish_inspect_understack.py, python/ironic-understack/ironic_understack/resource_class.py, python/ironic-understack/pyproject.toml, python/neutron-understack/neutron_understack/neutron_understack_mech.py, python/neutron-understack/neutron_understack/vlan_manager.py, python/neutron-understack/pyproject.toml, python/understack-flavor-matcher/pyproject.toml, python/understack-workflows/pyproject.toml, python/understack-workflows/understack_workflows/bmc_bios.py, python/understack-workflows/understack_workflows/bmc_chassis_info.py, python/understack-workflows/understack_workflows/bmc_credentials.py, python/understack-workflows/understack_workflows/bmc_hostname.py, python/understack-workflows/understack_workflows/bmc_network_config.py, python/understack-workflows/understack_workflows/bmc_settings.py, python/understack-workflows/understack_workflows/discover.py, python/understack-workflows/understack_workflows/flavor_detect.py, python/understack-workflows/understack_workflows/ironic_node.py, python/understack-workflows/understack_workflows/main/enroll_server.py, python/understack-workflows/understack_workflows/main/sync_keystone.py, python/understack-workflows/understack_workflows/main/undersync_device.py, python/understack-workflows/understack_workflows/main/undersync_switch.py, python/understack-workflows/understack_workflows/nautobot.py, python/understack-workflows/understack_workflows/nautobot_device.py, python/understack-workflows/understack_workflows/sync_interfaces.py
Enable more lints for checking our logging usage.
=> fix(python): enable ruff lints for logs

python/understack-workflows/understack_workflows/bmc_bios.py, python/understack-workflows/understack_workflows/bmc_credentials.py
simplify re-raising the exception
=> chore: simplify re-raising the exception

docs/operator-guide/troubleshooting-osh.md
Adds a pre-requisite step needed for helm template.
=> docs: updates troubleshooting openstack-helm operator guide

.github/renovate.json, apps/appsets/openstack.yaml
Change how we detect version changes for OpenStack Helm by using the helm data source template.
=> fix(renovate): change the OpenStack Helm version method

apps/appsets/openstack.yaml
https://tarballs.opendev.org/openstack/openstack-helm/
=> chore: update openstack-helm versions of horizon and placement

python/neutron-understack/neutron_understack/nautobot.py, python/neutron-understack/neutron_understack/neutron_understack_mech.py, python/neutron-understack/neutron_understack/tests/test_neutron_understack_mech.py
see https://rackspace.atlassian.net/browse/PUC-803
=> fix: when creating Nautobot prefixes, set their Tenant

examples/terraform-trunk-ports/.gitignore, examples/terraform-trunk-ports/README.md, examples/terraform-trunk-ports/main.tf, examples/terraform-trunk-ports/variables.tf, examples/terraform-trunk-ports/versions.tf
Adds terraform for building servers with trunk ports
=> feat: Adds terraform for building servers with trunk ports

components/nautobot/values.yaml
=> fix: Increase resources for nautobot to prevent high CPU throttling

workflows/openstack/eventsources/rabbitmq-user-argo-ironic.yaml, workflows/openstack/eventsources/rabbitmq-user-argo-keystone.yaml
=> fix(workflows): incorrect rabbitmq user ref in e4f2c52b

apps/appsets/components.yaml, components/nautobot/values.yaml
chore: Update nautobot helm chart version to the latest
=> chore: Update nautobot helm chart version to the latest

.github/workflows/containers.yaml
We want to build our containers when we make a tag.
=> ci: build our containers on tags as well

apps/appsets/understack.yaml
CVE-2025-1097, CVE-2025-1098, CVE-2025-24514 and CVE-2025-1974
=> chore(ingress-nginx): 4.9.1 -> 4.12.1

apps/appsets/appset-understack-infra.yaml, apps/appsets/appset-understack-operators.yaml, apps/appsets/components.yaml, apps/appsets/infra.yaml, apps/appsets/openstack.yaml, apps/appsets/operators.yaml, apps/appsets/project-understack-infra.yaml, apps/appsets/project-understack-operators.yaml, apps/appsets/project-understack.yaml, apps/kustomization.yaml
The newer layout allows us to split things based on if they are regional or if they are global so we need to get ourselves inline with that change.
Please read the commit messages for the individual changes to understand the differences and the changes.
=> chore(argocd): attempt to get things more inline with the newer layout

docs/operator-guide/ovs-ovn.md
docs: Adds guide for troubleshooting OVN and NeutronAgentDown alerts
=> docs: Adds guide for troubleshooting OVN and NeutronAgentDown alerts

apps/appsets/understack.yaml
That will help on the migration from the old appsets to the new.
=> feat: Added a finalizer and preservation of resources on deletion on the understack appset

python/understack-workflows/tests/test_sync_interfaces.py, python/understack-workflows/understack_workflows/sync_interfaces.py
Adding a missing test in advance of changing this code
=> chore: Add Unit Test for sync_interfaces (enroll functionality)

python/neutron-understack/neutron_understack/ml2_type_annotations.py
=> fix(neutron): resolve crash because of missing typings

workflows/argo-events/workflowtemplates/enroll-server.yaml
[workflow in dev](https://workflows.dev.undercloud.rackspace.net/workflows/argo-events/enroll-server-inspect-2js5f?tab=workflow&nodePanelView=inputs-outputs&uid=3bdba446-9c6e-479f-8b91-c512c753176d)
=> feat:PUC-662: adding Ironic redfish inspection step

python/neutron-understack/neutron_understack/ml2_type_annotations.py, python/neutron-understack/neutron_understack/neutron_understack_mech.py, python/neutron-understack/neutron_understack/utils.py
Part 1 of refactor - adjust mechanism driver to specifically deal with baremetal ports
=> feat: refactor mechanism driver part 1

docs/design-guide/neutron-networking.md
Thanks to @skrobul for some feedback on improved wording on this document.
=> docs: updated the network design based on reviews

docs/design-guide/neutron-networking.md
Added a diagram to help provide details on how port creation and update operations happen within OpenStack Neutron.
=> docs: add diagram showing port create and update in neutron

.github/renovate/matchOpenStackHelm.json
=> chore: fix up renovate rules for OpenStack Helm

docs/deploy-guide/deploy-repo.md
Added some notes about the helm values file naming for deployments.
=> docs: add notes about helm values file naming

python/neutron-understack/neutron_understack/neutron_understack_mech.py
Added a basic debug log line when a port creation comes into the mechanism.
=> chore(neutron): add a debug log when a port is created

.github/renovate/matchOpenStackHelm.json
Used a test repo to set this up and iterate on it until it gave the results we want.
https://developer.mend.io/github/cardoe/renovate-test
https://github.com/cardoe/renovate-test/pull/5
https://github.com/cardoe/renovate-test/pull/6
https://github.com/cardoe/renovate-test/pull/7
=> fix: renovate configs for OpenStack Helm now work

components/glance/values.yaml, components/horizon/values.yaml, components/ironic/values.yaml, components/keystone/values.yaml, components/neutron/values.yaml, components/nova/values.yaml, components/placement/values.yaml, components/skyline/values.yaml
Since we are using Server Side Apply and Server Side Diff, we need to drop the Replace=True which is causing deploys to get hung.
ref: https://github.com/argoproj/argo-cd/issues/11573
ref: https://github.com/argoproj/argo-cd/issues/11574
=> fix(argocd): updating OpenStack jobs with SSA

components/openstack/memcached-values.yaml
References:
* https://github.com/bitnami/charts/blob/main/bitnami/memcached/values.yaml#L218-L234
* https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15-L44
=> fix: Increase resources for memcached due to hitting CPUThrottlingHigh alerts

components/openstack-exporter/values.yaml
Mechnical move from deploy repo to this repo.
=> fix(openstack-exporter): Tuning to help with metric gaps

apps/appsets/appset-understack-global.yaml, apps/appsets/appset-understack-infra.yaml, apps/appsets/appset-understack-openstack.yaml, apps/appsets/appset-understack-operators.yaml, apps/appsets/appset-understack-site.yaml
Set the defaults so that they deploy from this repo with the expectation that you will override this in any further configuration you will do to these values.
=> fix(appset): set defaults to deploy from this repo

python/neutron-understack/neutron_understack/l3_router/svi.py
This plugin is a stub for on fabric anycast based SVI gateways.
=> feat(neutron): add stub SVI router flavor plugin

apps/infra/sealed-secrets.yaml
add sealed secrets to infra appset
=> fix: add sealed secrets to infra appset

docs/deploy-guide/gitops-install.md, docs/deploy-guide/requirements.md, docs/index.md, mkdocs.yml
Updates to the documentation landing page and deployment requirements page.
=> docs(cleanup): Cleans up and updates landing page and deploy guide

components/ironic/values.yaml
… [Errno 18] Invalid cross-device link
=> fix: Failed to prepare node for cleaning: Could not link image error: [Errno 18] Invalid cross-device link

python/cinder-understack/cinder_understack/dynamic_netapp_driver.py
https://rackspace.atlassian.net/browse/PUC-1110
cinder.volume.configuration module to abstract conf registration
Fixed the parttern where it data-svm1 and data-svm2 had different mount paths for their pools
=> feat: Step 4.1: cinder.volume.configuration module to abstract conf registration 

bootstrap/argocd/components/sso/external-secret-argocd-sso.yaml, components/argo-events/secret-netapp.yaml, components/argo/external-secret-argo-sso.yaml, components/cinder/cinder-volume-netapp.yaml, components/dex/secretstore-dex.yaml, components/keystone/external-secret-keystone-sso.yaml, components/nautobot/external-secret-nautobot-sso.yaml, components/nautobot/secretstore-nautobot.yaml, components/neutron/neutron-nautobot.yaml, components/openstack/templates/secretstore-openstack.yaml.tpl, components/openstack/templates/svc-acct-argoworkflow.yaml.tpl, components/openstack/values.yaml, operators/monitoring/external-secret-grafana-sso.yaml, workflows/argo-events/secrets/nautobot-token.yaml, workflows/argo-events/secrets/openstack-svc-acct.yaml, workflows/openstack/secrets/nautobot-token.yaml, workflows/openstack/secrets/openstack-svc-acct.yaml
Updates the external-secrets CRs to version v1 in preparation for updating external-secrets to version 0.17+.
=> chore(deps): update external-secrets CRD API version to v1

bootstrap/argocd/values.yaml
This allows temporarily disabling the applicaiton selfHeal
=> chore(argocd): allow ucadmins to edit applications

apps/appsets/appset-understack-site.yaml
This is an unfortunate hack that needs to be updated with a better approach.
=> fix(apps): add dns_zone workaround for site as well

python/cinder-understack/cinder_understack/dynamic_netapp_driver.py, python/cinder-understack/cinder_understack/tests/test_dynamic_netapp_driver.py
https://rackspace.atlassian.net/browse/PUC-1145
single FixedIntervalLoopingCall in the parent driver (NetappCinderDynamicDriver)
=> feat: Add task to looping calls to discover new SVMs every 5 minutes

.typos.toml, components/ironic/configmap-ironic-bin.yaml, components/ironic/kustomization.yaml, components/ironic/values.yaml
These changes should have happened to ironic as part of #1235 and were missed. These are those fixes.
=> fix(ironic): includes fixes that were missed from #1235
