README.md
bootstrap/kustomization.yaml
components/10-keystone/README.md
scripts/easy-secrets-gen.sh

Added a helper to make it easier to deploy secrets. Fix the fact that sealed-secrets wasn't deployed. Fix the URL for the OpenStack client pod.

fix: documentation and easy mode secrets

---

operators/messaging-topology-operator/kustomization.yaml

The RabbitMQ operator defines the namespace and the messaging topology operator defines it as well. This causes ArgoCD to fight over which Application deployment owns the namespace. Since the messaging topology operator depends on the RabbitMQ operator, just define it there once. fixes PUC-170

fix: avoid defining rabbitmq-system namespace twice

---

bootstrap/README.md
bootstrap/argocd/ingress.yaml
bootstrap/argocd/kustomization.yaml
bootstrap/cert-manager/issuer-kube-system-self-signed.yaml
bootstrap/cert-manager/kustomization.yaml
bootstrap/ingress-nginx/kustomization.yaml
bootstrap/ingress-nginx/namespace.yaml
bootstrap/ingress-nginx/values.yaml
bootstrap/kustomization.yaml
components/09-nautobot/base/kustomization.yaml
components/09-nautobot/base/nautobot/templates/ingress.yaml
components/09-nautobot/values.yaml

Adds ingress-nginx to be deployed into a cluster and enables Nautobot and ArgoCD to use it

feat: add ingress-nginx and enable argocd and nautobot to use it

---

.github/workflows/yamllint.yaml
components/10-keystone/README.md
scripts/openstack-helm-sealed-secrets.sh

Added checks to generated Kubernetes configs. Correct a docs mistake and ensure a script doesn't fail.

ci: add checks to generated Kubernetes configs

---

apps/components/argo-workflow.yaml
apps/components/argocd-understack-project.yaml
components/00-namespaces/argo-workflow.yaml
components/00-namespaces/kustomization.yaml
components/11-argo-workflow/kustomization.yaml

Adds argo-workflow as a component.  This is not adding events or the workflows yet.  It's just setting up the workflow namespace and environment to be used.  New workflow namespace is configured as "argo".

feat: add component argo workflow

---

README.md
bootstrap/cert-manager/kustomization.yaml
components/10-keystone/README.md
scripts/easy-secrets-gen.sh
shell.nix

This PR addresses some of the issues I have found when trying to deploy this on clean cluster.

fix: Various improvement and fixes found in 1st test deployment

---

apps/components/ironic.yaml
apps/components/kustomization.yaml
components/01-secrets/README.md
components/13-ironic/README.md
components/13-ironic/aio-values.yaml
components/13-ironic/ironic-mariadb-db.yaml
components/13-ironic/ironic-rabbitmq-queue.yaml
components/13-ironic/kustomization.yaml

Create an initial configuration to install OpenStack Ironic. The PXE service right now binds to the host's network device so this configuration won't work on all systems but it's a first step in getting this deployed.

feat: add installation of OpenStack Ironic

---

components/10-keystone/README.md
components/10-keystone/aio-values.yaml
components/13-ironic/README.md
components/13-ironic/aio-values.yaml
components/openstack-2023.1-jammy.yaml

Rather than having to maintain and keep up with different override files for OpenStack Helm's containers, centralize it into one file that can be shared between all the components.

feat: use a common container list for OSH

---

README.md
apps/components/dexidp.yaml
components/09-nautobot/base/kustomization.yaml
components/09-nautobot/base/nautobot/templates/configmap.yaml
components/09-nautobot/base/nautobot/templates/dexauth-cm.yaml
components/09-nautobot/base/nautobot/templates/nautobot-deployment.yaml
components/13-dexidp/README.md
components/13-dexidp/kustomization.yaml
components/13-dexidp/namespace.yaml
components/13-dexidp/values.yaml
scripts/patch-coredns.sh

Adds Dex IDP and lets Nautobot use it to authenticate users against Keystone so the same users are used across the entire stack. Closes https://rackspace.atlassian.net/browse/PUC-167

feat: DexIDP Integration for Nautobot

---

components/10-keystone/aio-values.yaml

The `rxt` auth plugins are not available after we switched to generic upstream docker images for Keystone in #17.
Fixes:
```
2024-03-13 17:54:22.798 14 CRITICAL keystone [-] Unhandled error: stevedore.exception.NoMatches: No 'keystone.auth.password' driver found, looking for 'rxt'
2024-03-13 17:54:22.798 14 ERROR keystone Traceback (most recent call last):
2024-03-13 17:54:22.798 14 ERROR keystone   File "/var/lib/openstack/bin/keystone-manage", line 8, in <module>
2024-03-13 17:54:22.798 14 ERROR keystone     sys.exit(main())
2024-03-13 17:54:22.798 14 ERROR keystone   File "/var/lib/openstack/lib/python3.10/site-packages/keystone/cmd/manage.py", line 41, in main
2024-03-13 17:54:22.798 14 ERROR keystone     cli.main(argv=sys.argv, developer_config_file=developer_config)
2024-03-13 …
```

fix: keystone is missing rxt plugin

---

components/11-argo-workflows/argo-server-cluster-role.yaml
components/11-argo-workflows/ingress.yaml
components/11-argo-workflows/kustomization.yaml
components/11-argo-workflows/patch-server-deployment.yaml
components/11-argo-workflows/patch-workflow-deployment.yaml
components/12-argo-events/argo-role.yaml
components/12-argo-events/argo-server-role.yaml
components/12-argo-events/default-role.yaml
components/12-argo-events/kustomization.yaml
components/12-argo-events/native-eventbus.yaml
components/12-argo-events/sensor-workflow-role.yaml
components/12-argo-events/webhook-event-source.yaml
components/12-argo-events/webhook-sensor.yaml
components/12-argo-events/workflow-role.yaml

This creates basic argo-workflow and argo-events deployments
- deploys argo-workflows in namespaced mode
- argo-workflows controller monitors argo-events namespace
- does not configure auth for argo-workflows
- creates a single EventSource for a webhook event on POSTs to /nautobot
- creates a single Sensor with dependency on the event described above which defines a single hello-world Workflow trigger

feat: argo-workflows and argo-events deployments (JIRA:PUC-193)

---

components/10-keystone/README.md
components/10-keystone/kustomization.yaml
components/13-ironic/README.md
components/13-ironic/kustomization.yaml
components/openstack-secrets.tpl.yaml
docs/install-understack-ubuntu-k3s.md
scripts/gen-os-secrets.sh

Generate a helm values file with the secrets in it. That can then be stored and used via tools like https://github.com/jkroepke/helm-secrets Then switch to using the OpenStack Helm charts via their repo so that we can execute their helm charts like we do the other components.

feat: load secrets for OpenStack Helm via a values file

---

components/openstack-secrets.tpl.yaml
scripts/gen-os-secrets.sh

OpenStack Helm will always randomly generate this value if we don't use a constant memcache token secret in our config. This causes the secrets to always change and their annotations to change which restarts all containers from OpenStack Helm every time. This should allow us to maintain the container configs as idempotent.

feat: generate memcache token secret to be constant

---

components/09-nautobot/base/nautobot/templates/configmap.yaml
components/13-dexidp/values.yaml

Following the changes in the Enterprise Application config for Nautobot, this PR adds support for recognising the groups sent as `roles` claim when authenticating through Dex.
The identity token should contain `roles` claim with `undercloud-dev` for a particular set of privileged users (usually mapped to one or more AD groups) and can be empty for everyone else.

feat: AzureAAD groups support

---

components/12-argo-events/kustomization.yaml

This configMapGenerator was accidentally added in d3e9d90f - it should have been added only to the argo-workflows/kustomization.yaml. Fixes:
```
❯ k -n argocd describe app argo-events
Name:         argo-events
Namespace:    argocd
<snip>
Self Heal:  true
Status:
Conditions:
Last Transition Time:  2024-04-04T11:49:52Z
Message:               Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): `kustomize build <path to cached source>/components/12-argo-events --enable-helm` failed exit status 1: Error: loading KV pairs: file sources: [sso]: evalsymlink failure on '<path to cached source>/components/12-argo-events/sso' : lstat <path to cached source>/components/12-argo-events/sso: no such file or …
```

fix: argo-events: remove accidentally added configMapGenerator

---

mkdocs.yml

The docs are attempting to take advantage of these markdown extensions so we need to enable them.

docs: enable markdown extensions for the docs

---

apps/operators/ingress-nginx.yaml

The wrong project was used when it was moved into the operators bucket in b9040cef4.

fix: b9040cef4 ingress-nginxs argocd project

---

apps/components/argo-workflows.yaml

The argo server is currently configured to need the argo-sso secret to start up so include it in the template.

fix: include argo-sso secret for argo-workflows

---

components/09-nautobot/base/nautobot/templates/configmap.yaml

I need to be able to set django's `SOCIAL_AUTH_OIDC_OIDC_ENDPOINT` to a different url, but let's keep the existing default in place.

fix: makes nautobot oidc auth endpoint configurable

---

components/keystone/aio-values.yaml

The jobs cannot be run as pre steps because ArgoCD tries to run them before their dependent resources have been created.

fix: adjust hooks on keystone jobs

---

.github/workflows/containers.yaml
components/13-ironic/aio-values.yaml
components/13-ironic/dnsmasq-cm.yaml
components/13-ironic/dnsmasq-pvc.yaml
components/13-ironic/dnsmasq-ss.yaml
components/13-ironic/kustomization.yaml
components/openstack-2023.1-jammy.yaml
containers/Dockerfile.dnsmasq
containers/Dockerfile.ironic
containers/common/helpers.sh
containers/dnsmasq/dnsmasq.conf.j2
containers/dnsmasq/entry-point.sh

This PR adds dnsmasq installation to the `openstack` namespace. It will:
- hand out IP addresses to hosts that are provisioned with Ironic
- cooperate with Ironic for setting per-host options
- enable a DNS server that can resolve records for endpoint URLs returned by the OpenStack Identity service catalogue
In its current form, it supports only a single DHCP range/pool. Support for multiple pools will be added as a separate story as it requires more input parameters (MACs of the relays, range names, and potentially different DNS server IPs).
Closes PUC-225

feat: package up dnsmasq as a DNS and DHCP server

---

apps/components/argo-workflows.yaml

I'm not convinced this is the best approach here, but it works and is at least consistent with how we're handling the Nautobot ingress patches.

fix: patching sso configmap in workflows to template in correct domain

---

components/dexidp/values-azure.yaml
components/dexidp/values-generic.yaml
components/keystone/aio-values.yaml

The group `undercloud-dev` is used by nautobot and users in this group have elevated permissions. With dex integration, we can use the keystone group undercloud-dev to control access to nautobot.

feat: adds creation of demo user and undercloud-dev nautobot access group.

---

components/ironic/dnsmasq-pvc.yaml

The dnsmasq pod failed to start for me:
```
Events:
Type     Reason            Age                  From               Message
----     ------            ----                 ----               -------
Warning  FailedScheduling  17m                  default-scheduler  0/1 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling..
Warning  FailedScheduling  7m48s (x2 over 12m)  default-scheduler  0/1 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling..
```
The pvc stuck:
```
root@915966-utility01-ospcv2-iad:~# kubectl get pvc
NAME                            STATUS    VOLUME …
```

fix: Use default storageclass

---

components/ironic/aio-values.yaml

The upstream openstack-helm is already creating a hostPath volume for /var/lib/ironic: https://github.com/openstack/openstack-helm/blob/master/ironic/templates/statefulset-conductor.yaml#L257-L259 - but it's not creating the volume mount in all of the containers. Currently we're putting images in to the host's /var/lib/ironic directory in order to make them available for the ironic-conductor-http containers to serve.

fix: Adds volume mount for the /var/lib/ironic hostpath.

---

mkdocs.yml

Groups the current pages in to a couple categories, which cleans up the navigation bar a little.
Demo of my changes:
Here's the current one for reference:

feat: Re-organize documentation nav and categories

---

.github/workflows/mkdocs.yaml

I'm unable to manually start a github actions workflow to deploy documentation. The deploy step gets skipped due to workflow if statement.

fix: allow github  workflows to perform manual docs deployment

---

.github/workflows/containers.yaml
argo-workflows/generic/containers/Dockerfile.python312_alpine
components/ironic/dnsmasq-ss.yaml
containers/Dockerfile.dnsmasq

Turns out the Alpine project does not follow semver and changes the versioned upstream images after the fact, so we have to pin them to a specific sha256 to keep stable builds.
Closes PUC-241. Fixes [build failures like this one](https://github.com/rackerlabs/understack/actions/runs/8789533012/job/24119504196)

fix: dnsmasq: pin versions, switch to debian

---

README.md
docs/gitops-install.md

Some of the things in the old README were outdated and no longer worked. This updates the install guide to use the gitops based install: https://rackerlabs.github.io/understack/gitops-install/

fix: Updates README to point to the GitOps based install guide.

---

apps/operators/mariadb-operator.yaml
apps/operators/messaging-topology-operator.yaml
apps/operators/postgres-operator.yaml
apps/operators/rabbitmq-operator.yaml

The operators templates used the wrong repo reference so the wrong branch was referenced when the templates were generated.

fix: use the correct repo reference for operators

---

components/ironic/aio-values.yaml

provide a shared place that we can mount data into the various ironic conductor pods

fix: pull in fix for ironic conductor mount points

---

docs/install-understack-ubuntu-k3s.md

We were manually setting the node labels required by openstack-helm, but we can set them when we install k3s.
```bash
root@nick-understack-test-20240429:/var/log# kubectl describe node/nick-understack-test-20240429
Name:               nick-understack-test-20240429
Roles:              control-plane,master
Labels:             beta.kubernetes.io/arch=amd64
beta.kubernetes.io/instance-type=k3s
beta.kubernetes.io/os=linux
kubernetes.io/arch=amd64
kubernetes.io/hostname=nick-understack-test-20240429
kubernetes.io/os=linux
node-role.kubernetes.io/control-plane=true
node-role.kubernetes.io/master=true
node.kubernetes.io/instance-type=k3s
openstack-control-plane=enabled  # <--------------------
```

fix: Updates k3s install option to automatically set the openstack node label

---

argo-workflows/ironic-nautobot-sync/sensors/nautobot-interface-update-sensor.yaml

This sensor configuration was accidentally overwritten, most likely during rebase/cleanup. It was using the 'whalesay' only for debugging and initial development and should normally refer to `synchronize-server-to-ironic` as defined in the WorkflowTemplate.

fix: nautobot-interface-update-sensor

---

apps/operators/rabbitmq-operator.yaml
docs/gitops-install.md

Fixed a typo in the rabbitmq-operator template and added a note about ref variables

fix: fix typo and add a note about ref variables

---

bootstrap/argocd/values.yaml
components/dexidp/values-azure.yaml
components/dexidp/values-generic.yaml
components/dexidp/values.tpl.yaml
components/keystone/aio-values.yaml
components/nautobot/dexauth-cm.yaml
components/nautobot/nautobot_config.py
docs/auth.md
docs/gitops-install.md
mkdocs.yml
scripts/easy-secrets-gen.sh

This refactors authentication to flow more through Dex and then allows operators/users to be added via Dex connectors to the system. Service accounts can be created within Keystone to have service to service authentication in the future as well.

feat: refactor authentication to be more integrated through Dex

---

docs/gitops-install.md
scripts/gitops-deploy.sh
scripts/gitops-secrets-gen.sh

This makes the GitOps scripts paths relative so anyone should be able to re-run these scripts on their machines.

feat: make script paths relative

---

docs/gitops-install.md
scripts/gitops-deploy.sh
scripts/gitops-secrets-gen.sh

Ensure that the UC_REPO variable is set to the top-level of the repo even if the environment variable file overwrites it. Suggest how the UC_DEPLOY variable can be set to the path to the git repo. fixes #80

fix: ensure UC_REPO/UC_DEPLOY are set correctly

---

scripts/gitops-secrets-gen.sh

Don't overwrite the metallb secret with the config data if it already exists.

fix: only create metallb secret if it doesn't exist

---

docs/networking.md
mkdocs.yml

Adds a new `Networking` section to the docs, with sub-sections for metallb and dhcp configuration settings.

feat: add documentation for networking, metallb, and dhcp related settings.

---

.github/workflows/build-container-images.yaml
argo-workflows/nautobot-interface-sync/code/helpers.py
argo-workflows/nautobot-interface-sync/code/models.py
argo-workflows/nautobot-interface-sync/code/nautobot.py
argo-workflows/nautobot-interface-sync/code/sync_nautobot_interfaces.py
argo-workflows/nautobot-interface-sync/containers/Dockerfile.nautobot_int_sync
argo-workflows/nautobot-interface-sync/containers/requirements.txt
argo-workflows/nautobot-interface-sync/deps/get-obm-creds.yaml
argo-workflows/nautobot-interface-sync/deps/nautobot-token-secret.yaml
argo-workflows/nautobot-interface-sync/deps/obm-creds-secret.yaml
argo-workflows/nautobot-interface-sync/docs/README.md
argo-workflows/nautobot-interface-sync/sensors/nautobot-interface-update-sensor-int-sync.yaml
argo-workflows/nautobot-interface-sync/workflowtemplates/synchronize-interfaces-to-nautobot.yaml

The purpose of the workflow templates in this folder is to create or update device interfaces in Nautobot from Redfish info that we get from a device using OBM credentials.
Closes PUC-199

feat: Nautobot interface sync

---

docs/install-understack-ubuntu-k3s.md

Updates the k3s install options.

docs: Updates k3s install options in install guide

---

containers/dnsmasq/dnsmasq.conf.j2

Now that we have the Ironic integration, the option 67 is set twice - once to 'nonexistent.file' and second time through the options file delivered by Ironic. In other words, the default is not overwritten but the second instance of the same option gets appended to the response.

fix: dnsmasq: do not set default bootfile

---

.github/workflows/containers.yaml
components/ironic/dnsmasq-cm.yaml
components/ironic/dnsmasq-ss.yaml
containers/Dockerfile.dnsmasq
containers/dnsmasq/dnsmasq.conf.j2

Allow dnsmasq to bind to a specific interface. Stop using the 0.0.1 version for the main branch and let the image pull policy default.

feat: allow interface binding and drop specific version

---

components/ironic/dnsmasq-ss.yaml
containers/dnsmasq/dnsmasq.conf.j2

Now that we are serving the TFTP from the dnsmasq container, this PR adds an option to configure a directory that is not part of the read-only root filesystem of the container, but uses a host mapped volume instead.

fix: dnsmasq: mount /var/lib/understack/master_iso_images

---

apps/components/ironic.yaml

The helm chart has updates to allow us to disable the pxe and http container in the conductor. Since we're running dnsmasq ourselves for the pxe service so we need to be able to disable the one in the conductor.

feat: update to latest helm chart version

---

components/nautobot/values.yaml

The helm chart already includes this secret into the containers so we don't need to provide it as an extra secret because it is being double included.

fix: remove providing nautobot-env explicitly

---

argo-workflows/nautobot-interface-sync/code/helpers.py
argo-workflows/nautobot-interface-sync/code/models.py

fix: search for integrated interfaces and adjust mac addr extraction
So as it turns out, Dell redfish is reporting "Integrated" interfaces, but these are actually add-ons so we need to include those when creating interfaces for servers in Nautobot.
Same case is for HP, these are using "Embedded ALOM" as one of their expansion ports.
In both cases, the only true onboard interfaces are designated as "Embedded",  which we filter out now correctly.
Another small issue this PR fixes is mac addr extraction, Dell in redfish is providing a list of all NIC mac addresses when querying the port, which is incorrect, so instead we now search in system resources to get the mac addr.

fix: search for integrated interfaces and adjust mac addr extraction

---

.pre-commit-config.yaml

Utilize pre-commit to validate the argo workflows and argo workflow templates against the published JSON schema.

ci: check argo workflows and workflow templates in pre-commit

---

components/ironic/aio-values.yaml

https://docs.openstack.org/ironic/latest/admin/drivers/redfish.html#redfish-http-s-boot

feat: Enable openstack ironic redfish-https boot interface.

---

containers/dnsmasq/dnsmasq.conf.j2

If the dhcp-proxy value is going to be empty, don't template it out.

fix: don't make bad dnsmasq config for dhcp-proxy

---

apps/appsets/operators/service.yaml
apps/appsets/operators/undersync.yaml
components/undersync/deployment.yaml

Caveat:  I have no real idea what I'm doing with this stuff and I wasn't able to test this out.
https://rackspace.atlassian.net/browse/PUC-349
"Argo (understack) should reference undersync repo to get this deployed as one of the required apps. Doesn’t necessarily need to be through the app of apps, but needs to be deployed in the IAD Dev environment."

chore: Add ApplicationSet and Deployment for Undersync

---

apps/appsets/openstack/openstack.yaml

Bump to pull in https://review.opendev.org/c/openstack/openstack-helm/+/923325 to fix Neutron auth to Ironic

fix: bump OSH Neutron for Ironic auth

---

argo-workflows/ironic-nautobot-sync/sensors/nautobot-interface-update-sensor.yaml
argo-workflows/nautobot-interface-sync/sensors/nautobot-interface-update-sensor-int-sync.yaml

These fields are actually objects and not strings. The intention was probably to ensure that there is an IP address assigned to this interface so this updates to check the 'address' key inside of the object for a value.

fix: adjust workflow sensors filtering

---

operators/external-secrets/kustomization.yaml

There were some fixes with the webhook provider that were landed in 0.9.20 that we noticed in 0.9.19 so bump to the latest version to get those.

fix: bump external-secrets to get webhook fixes

---

.github/workflows/containers.yaml

Make the building of our OpenStack project containers a bit more generic so we can add others in the future. Make it that we always pull the container image rather than using what the builder might have cached.

feat: clean up OpenStack container building

---

components/keystone/aio-values.yaml

The argoworkflow user was being created in a cluster override and only getting created in one dev cluster instead of all of them.

fix: fix keystone bootstrap to include all necessary users

---

components/keystone/aio-values.yaml

The demo user was being added to the demo project, which doesn't appear to exist. It should instead be added to to the undercloud project. fix e90ecc099. ref #150

fix: add demo user to the undercloud project

---

components/ironic/aio-values.yaml

Reference: https://docs.openstack.org/ironic/latest/admin/drivers/idrac.html
Error I'm seeing when attempting to use idrac: 
```
No valid host was found. Reason: No conductor service registered which supports driver idrac for conductor group "". Ensure the driver is valid and enabled. (HTTP 400)
```

feat: Enables ironic idrac interface

---

apps/appsets/cert-manager.yaml

The acme-dns secret in the deploy repo wasn't getting pulled in. This fixes it.

feat: updates cert manager to include deploy secrets

---

components/ironic/aio-values.yaml

Our plan is to focus on Redfish enabled hardware, with an understanding that we'll need iDRAC and iLO overrides so enable everything necessary to facilitate this. Don't set defaults to avoid interference with the hardware types and add some notes to avoid an issue in the future.

feat: enable all Ironic interfaces needed

---

containers/Dockerfile.ironic

The iLO and iDRAC specific backends require the OEM interface packages to be functional.

fix: Ironic support iDRAC and iLO Redfish OEM interfaces

---

containers/Dockerfile.ironic

Reverts rackerlabs/understack#170. Causing the pod to crash.

fix: revert Ironic support iDRAC and iLO Redfish OEM interfaces

---

containers/Dockerfile.ironic

The container is crashing with no output when it attempts to load hardware types so remove the proliant bits as a guess.

fix: remove proliant OEM driver for Ironic

---

.github/workflows/build-container-images.yaml
argo-workflows/ironic-to-nautobot-sync/code/helpers.py
argo-workflows/ironic-to-nautobot-sync/code/main.py
argo-workflows/ironic-to-nautobot-sync/code/nautobot.py
argo-workflows/ironic-to-nautobot-sync/containers/Dockerfile
argo-workflows/ironic-to-nautobot-sync/containers/requirements.txt
argo-workflows/ironic-to-nautobot-sync/sensors/ironic-to-nautobot-sensor.yaml
argo-workflows/ironic-to-nautobot-sync/workflowtemplates/sync.yaml

This PR adds a workflow and related sensor that listens to the RabbitMQ messages from Ironic (enabled for dev in https://github.com/RSS-Engineering/undercloud-deploy/pull/94) and every time the node in Ironic is updated, the status is synchronized back to the Nautobot.
While this works as is, I don't feel super good about storing the `provision_state` in the `status` field in the Nautobot. I would appreciate some thoughts and feedback on this.
Here is what I was debating:
Pros: easy to implement, immediately visible in various places in the UI. Does not require schema changes. The history of changes is automatically tracked.
Cons: bloat in the number of possible statuses (Ironic has 25 of them). Will still require ansible changes to prepopulate Status choices.
Pros: relatively easy to …

feat: Synchronize Ironic `provision_state` to Nautobot 

---

apps/appsets/workflows.yaml

We have removed the deps dir from appset workflow yaml as the files in them supposed to be overwritten from external repos and are left there as an example how the yamls should look like. The generic deps directory files however are needed.

fix: add deps dir from generic argo wf

---

components/ironic/aio-values.yaml

When we use the iDRAC driver in Ironic and need to use the virtual media boot interface, we must use the idrac-redfish-virtual-media interface which wasn't enabled. So enable it. At the same time scrape the list to better target what we want to support and use going forward.

fix: Ironic enable iDRAC virtual media and remove unnecessary interfaces

---

components/ironic/aio-values.yaml

The ilo driver needs the no-firmware interface so re-enable that from d1bcab66d.

fix: Ironic ilo firmware interface support

---

components/ironic/aio-values.yaml

ilo hw type requires agent or no-raid raid interface

fix: Enable agent raid interface for Ironic

---

components/ironic/aio-values.yaml

Enable the new ironic inspector that is in tree and enable the hooks necessary to run LLDP and populate data about our devices from that LLDP data.
see the following for more info:
https://docs.openstack.org/ironic/latest/admin/inspection.html
https://docs.openstack.org/ironic/latest/admin/inspection/managed.html
https://docs.openstack.org/ironic/latest/admin/inspection/hooks.html

feat: enable new ironic inspector and enable LLDP data from it

---

python/neutron-understack/neutron_understack/neutron_understack_mech.py

We were not able to get Neutron into a state where it would wait for the `undersync-device` workflow to complete and react to the potential errors.
We have tried few variations:
- putting the `_move_to_network()` into a separate greenthread and periodically polling with greenthread.sleep(). This has made the workflow run in the background, but the whole Neutron instance has blocked
- similarly, replacing synchronous `time.sleep` with `greenthread.sleep` did not make any difference.
- initial Workflow trigger has been placed in the `bind_port` instead of `update_port_postcommit`. This also resulted in whole Neutron instance being blocked.
Finally we decided to simply fire the workflow and not check for the result and rely on other mechanisms to be notified about potential errors.
Related …

feat: neutron/undersync: change to fire & forget

---

.github/workflows/containers.yaml
containers/Dockerfile.ironic-nautobot-client
python/understack-workflows/understack_workflows/main/sync_nautobot_interfaces.py

The common container didn't install the package which was the whole point. Fixed up a bad module import. Fixed the container tagging to match the style we want to use. fixes issues introduced in #184

fix: correct issues with the common container

---

.github/workflows/containers.yaml
python/understack-workflows/understack_workflows/main/sync_nautobot_interfaces.py

Removed exit_with_error previously so need to get rid of this usage. Make sure the containers are rebuilt when the python code gets changed.

fix: keep fixing these containers

---

python/understack-workflows/tests/json_samples/event-interface-update.json
python/understack-workflows/tests/test_node_config.py
python/understack-workflows/understack_workflows/main/synchronize_obm_creds.py
python/understack-workflows/understack_workflows/main/synchronize_server.py
python/understack-workflows/understack_workflows/node_configuration.py
python/understack-workflows/understack_workflows/redfish_driver_info.py

Refactored the create/update of the ironic node from the Nautobot data. Include code to adjust how we ensure that the driver and interfaces are set correctly. This partially grows out of #168 but doesn't include the full driver detection from Nautobot.

feat: refactor ironic node create/update and setting of interfaces

---

components/nova/aio-values.yaml

Currently we do not have the nova metadata API hooked up to machines so just force config_drive always so that users get a happier experience by default.

fix: enable config_drive in nova always

---

python/neutron-understack/neutron_understack/neutron_understack_mech.py

typing.Union is no longer required as of python 3.10 and set notation may now be used. This resulted in a few other formatting changes.

chore: fix type annotations

---

argo-workflows/shared-sensors/nb-oob-interface-update-sensor.yaml
argo-workflows/sync-nb-server-to-ironic/workflowtemplates/sync-nb-server-to-ironic.yaml
argo-workflows/sync-nb-server-to-ironic/workflowtemplates/synchronize-obm-creds.yaml
argo-workflows/sync-srv-redfish-intfs-to-nb/workflowtemplates/sync-interfaces-to-nautobot.yaml
argo-workflows/sync-srv-redfish-intfs-to-nb/workflowtemplates/sync-srv-redfish-intfs-to-nb.yaml
python/understack-workflows/tests/test_sync_nautobot_interfaces.py
python/understack-workflows/understack_workflows/helpers.py
python/understack-workflows/understack_workflows/main/sync_nautobot_interfaces.py
python/understack-workflows/understack_workflows/nautobot.py

Use the device ID / UUID which is a better identifier for us to use to find the device to sync the interfaces for. This saves us a trip to the Nautobot DB as well. In Nautobot the device name does not have to be unique so this avoids possible issues there. Added tests of the parser to make sure we get the correct data. Added types so we can have better tests in the future. Cleaned up the duplicate hostname usage in the workflow as well.

fix: stop using device name for interface sync

---

.github/workflows/containers.yaml
argo-workflows/shared-sensors/nb-oob-interface-update-sensor.yaml
python/understack-workflows/tests/test_node_config.py
python/understack-workflows/understack_workflows/node_configuration.py

Fixes e5e268c2f6 where the wrong parameter was put into the workflow. Fixed the add node code and added tests for it.

fix: sync interfaces errors

---

apps/appsets/argocd.yaml
bootstrap/argocd/components/sso/external-secret-argocd-sso.yaml
bootstrap/argocd/components/sso/kustomization.yaml
bootstrap/argocd/values.yaml
components/dex/secretstore-dex.yaml
components/nautobot/external-secret-nautobot-sso.yaml
components/nautobot/kustomization.yaml
docs/gitops-install.md
scripts/gitops-secrets-gen.sh

Instead of having to duplicate the SSO secrets between the dex namespace and the application specific namespaces, use the External Secrets Operator to copy it and keep it in sync for us. Broke up the ArgoCD SSO configuration into its own component to not have it broken on initial deploy and have to restart. This simplifies the docs as well.

feat: use External Secrets to configure SSO for apps

---

.pre-commit-config.yaml
docs/user-guide/openstack-image.md
mkdocs.yml

Added some information on how to use the OpenStack image command and enable a set of common features we use across all of our docs.

docs: add some OpenStack image docs and enable more mkdocs features

---

.github/workflows/yamllint.yaml
argo-workflows/.workflow_with_description.schema.json
argo-workflows/generic/workflowtemplates/get-device-nautobot.yaml
argo-workflows/generic/workflowtemplates/get-obm-creds.yaml
argo-workflows/generic/workflowtemplates/get-obm-ip.yaml
argo-workflows/generic/workflowtemplates/nautobot-api.yaml
argo-workflows/ironic-to-nautobot-sync/sensors/ironic-to-nautobot-sensor.yaml
argo-workflows/ironic-to-nautobot-sync/workflowtemplates/sync.yaml
argo-workflows/obm-utils/workflowtemplates/idrac-enable-network-boot.yaml
argo-workflows/obm-utils/workflowtemplates/obm-firmware-update.yaml
argo-workflows/obm-utils/workflowtemplates/obm-sync-creds.yaml
argo-workflows/shared-sensors/nb-oob-interface-update-sensor.yaml
argo-workflows/sync-nb-server-to-ironic/sensors/debug-sensor.yaml
argo-workflows/sync-nb-server-to-ironic/workflowtemplates/node-events.yaml
argo-workflows/sync-nb-server-to-ironic/workflowtemplates/sync-nb-server-to-ironic.yaml
argo-workflows/sync-nb-server-to-ironic/workflowtemplates/synchronize-interfaces-to-ironic.yaml
argo-workflows/sync-nb-server-to-ironic/workflowtemplates/synchronize-obm-creds.yaml
argo-workflows/sync-nb-server-to-ironic/workflowtemplates/synchronize-server-to-ironic.yaml
argo-workflows/sync-srv-redfish-intfs-to-nb/workflowtemplates/sync-interfaces-to-nautobot.yaml
argo-workflows/sync-srv-redfish-intfs-to-nb/workflowtemplates/sync-srv-redfish-intfs-to-nb.yaml
argo-workflows/trigger-undersync/workflowtemplates/undersync-device.yaml
argo-workflows/trigger-undersync/workflowtemplates/undersync-switch.yaml

- All Sensors and Workflows require some description now, ideally containing a reference to the file where they were defined.
- Adds descriptions
example CI failure: https://github.com/rackerlabs/understack/actions/runs/10407977498/job/28824377015

chore: workflows: add annotations for easier locating

---

.github/workflows/code-test.yaml
python/understack-workflows/understack_workflows/main/synchronize_interfaces.py
python/understack-workflows/understack_workflows/port_configuration.py

Set the nautobot interface name on the corresponding ironic port on the node.

feat: set interface/port names in ironic

---

apps/appsets/infra.yaml
components/ironic/aio-values.yaml

Two fixes that were needed when updating some of the deployments.

fix: disable ironic's pxe container and ensure correct ArgoCD template evaluations

---

components/nautobot/nautobot-values.yaml
scripts/gitops-secrets-gen.sh

Upstream nautobot helm uses and wants to control `nautobot-env` secret which we were also using. This changes ours to `nautobot-custom-env` instead.

fix: Switch to using nautobot-custom-env due to upstream nautobot helm chart overrides

---

apps/appsets/components.yaml

Due to the merge order in ArgoCD
https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-value-precedence we cannot set this value here otherwise it will ignore our valueFiles which will likely want to provide additional values. This data is now read out of the SSO secret so it does not need to be passed in as an extra variable.

fix: cannot set the nautobot extra envars due to merge order

---

scripts/gitops-secrets-gen.sh

Fix 95febd38ba5 by using eval since 'declare' requires 'declare -g' for this to work properly but that didn't come about until Bash 4.2 but macOS is stuck on Bash 3.2

fix(gitops-secret-gen): fix bash whoopsie in 95febd38ba5

---

containers/dnsmasq/dnsmasq.conf.j2

The default config does not have this value set resulting in an empty value being set and the dnsmasq server crashing on startup due to the invalid value.

fix(ironic): avoid dnsmasq crashing with default cfg

---

components/ironic/dnsmasq-ss.yaml

The dnsmasq image was moved into understack.

fix(ironic): use the correct dnsmasq image

---

components/openstack/kustomization.yaml

memcached needs to be deployed into the openstack namespace

fix(argocd): deploy memcached to openstack ns

---

components/nautobot/nautobot-values.yaml
operators/cnpg-system/kustomization.yaml
operators/cnpg-system/namespace.yaml

While troubleshooting some issues with the cloudnative-pg kustomize install, I figured it would be easier moving forward if we used the helm install instead, so we can configure it easier.

fix(cloudnative-pg): Switch to cloudnative-pg helm chart for better control of settings

---

apps/appsets/components.yaml
apps/appsets/infra.yaml
apps/understack-workflows/eventsource-openstack/argo-rabbitmq.yaml
apps/understack-workflows/eventsource-openstack/eventbus-default.yaml
apps/understack-workflows/eventsource-openstack/kustomization.yaml
apps/understack-workflows/eventsource-openstack/openstack-event-source.yaml
apps/understack-workflows/kustomization.yaml
components/argo-events/kustomization.yaml
components/argo-events/native-eventbus.yaml
scripts/gitops-secrets-gen.sh

Switched argo-events to run cluster wide since each namespace has its own resources. This makes it easier for us to not have to copy secrets around so removed that case. Updated the openstack event source to be narrower in access scope and use the generated credentials by the rabbitmq operator removing the need for a generated secret at all. Added a Pod Disruption Budget to the event bus so we do not lose events.

fix: improve argo-events and the openstack event source

---

apps/appsets/argocd-operators-project.yaml
operators/rook/kustomization.yaml
operators/rook/values-cluster.yaml
operators/rook/values-operator.yaml

This PR adds basic deployment of Rook so that we can use PVCs in the development cluster.
It has been tested on the new uc-iad3-dev and has deployed successfully:
```
❯   kubectl --namespace rook-ceph get cephcluster
NAME        DATADIRHOSTPATH   MONCOUNT   AGE     PHASE   MESSAGE                        HEALTH        EXTERNAL   FSID
rook-ceph   /var/lib/rook     2          9m12s   Ready   Cluster created successfully   HEALTH_WARN              8ea3e27d-f56a-4477-88de-e499ab5f1795
```
The Health Warning is related to an insufficient number of OSDs deployed because we only have two nodes but a minimum of three are required.
Partially delivers PUC-495

feat: Rook / Ceph deployment for our storage needs

---

.github/workflows/code-test.yaml

This allows forks to continue to work when the code coverage runs

ci: fix code coverage comments from forks

---

argo-workflows/trigger-undersync/workflowtemplates/undersync-device.yaml
python/neutron-understack/neutron_understack/neutron_understack_mech.py
python/neutron-understack/neutron_understack/tests/fixtures/neutron_update_port_postcommit.json
python/neutron-understack/neutron_understack/tests/test_neutron_understack_mech.py
python/understack-workflows/understack_workflows/main/undersync_device.py
python/understack-workflows/understack_workflows/nautobot.py

We used to flip a bit on the nautobot Device object for “connected_to_network”
when changing a device from/to “provisioning” and “tenant” settings.
We need this to be interface specific.  Because of Ironic's knowlege of the
interface that is being used for PXE boot, we are called with a server interface
UUID.
We update the nautobot status field of connected switch interface.
This tells undersync which mode the port should be in - provisioning or
tenant (normal).
This would be released in tandem with https://github.com/RSS-Engineering/undersync/pull/14 fixes PUC-425

feat: workflow updates Nautobot Interface.status instead of device.custom_field.conected_to_network

---

.gitignore
argo-workflows/sync-nb-server-to-ironic/workflowtemplates/sync-server-to-ironic.yaml
python/understack-workflows/understack_workflows/main/sync_server.py

Changes in this PR are:
1. Python code update to sync_server.py to return state of the ironic node
2. Argo workflow update to sync_server_to_ironic.yaml file to return output results for next steps to utilize.
fixes PUC-494

feat: update sync server workflow to return node state

---

apps/understack-workflows/eventsource-openstack/argo-rabbitmq.yaml

These permissions didn't work for the event source. Marek was correct in #248 / e77107de.

fix: permissions for rabbitmq didn't work

---

apps/appsets/openstack.yaml
components/keystone/aio-values.yaml
components/nova/aio-values.yaml
components/placement/aio-values.yaml

Release notes: https://github.com/openstack/openstack-helm/tree/master/releasenotes/notes
Most of the changes are minor. The glance chart has deprecated a couple settings but we aren't using them.

chore(openstack): Update OpenStack components to use the latest helm chart versions.

---

argo-workflows/obm-utils/workflowtemplates/obm-sync-creds.yaml

This should update the DRAC settings via DRAC to get Dell servers to PXE boot from the correct NICs - by default the dell BIOS is configured to use the built-in NICs but we don't cable those up, so we make this update to the BIOS settings that will cause it to use te add-in card instead.

feat: Add DRAC enable network boot process to existing workflow

---

.github/workflows/containers.yaml

When running our CI in a fork, we need to build the containers in the fork and not in our repository.

ci: fix container building for forks

---

.github/workflows/code-test.yaml

Enable code coverage reporting on neutron-understack and de-dup the rules.

ci: enable code coverage reporting on neutron-understack

---

python/ironic-understack/ironic_understack/resource_class.py

Without this, there is a race condition when the ironic_understack specific oslo_config parser is loaded. In some cases, the  redfish inspect interface is loaded first and the `CONF` constant is avaialable, whereas if `resource_class` is loaded first, it throws following exception:
```
1327172-hp1:/var/lib/openstack $ python
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ironic_understack.resource_class import UndercloudResourceClassHook
Traceback (most recent call last):
File "/var/lib/openstack/lib/python3.10/site-packages/oslo_config/cfg.py", line 2230, in __getattr__
return self._get(name)
File "/var/lib/openstack/lib/python3.10/site-packages/oslo_config/cfg.py", line 2664, in _get …
```

fix: ironic_understack: fix inspection hook loading

---

bootstrap/argocd/components/sso/external-secret-argocd-sso.yaml
components/argo/external-secret-argo-sso.yaml
components/keystone/external-secret-keystone-sso.yaml
components/nautobot/external-secret-nautobot-sso.yaml

These fields are set by external secrets when we apply these resources. When using ArgoCD and server side apply it causes ArgoCD to see these resources as always out of sync due to argoproj/argo-cd#13004

fix: add fields that external secrets changes

---

apps/appsets/operators.yaml

We are not using this anymore and the path is gone so remove it from the ArgoCD AppSet.

fix: fully delete old postgres operator

---

apps/appsets/workflows.yaml

These are applied via kustomize from the workflows directory via the components AppSet under the understack-workflows Application. This was a legacy glob apply which needs to ultimately go away.

fix: avoid double apply of workflows

---

components/keystone/aio-values.yaml

fix(keystone): fix annoying warning message about inconsistent indentation

---

apps/appsets/openstack.yaml

This is to allow setting websso_keystone_url
ref: https://review.opendev.org/c/openstack/openstack-helm/+/928957

chore: horizon: upgrade chart to 0.3.28

---

python/neutron-understack/neutron_understack/neutron_understack_mech.py
python/understack-workflows/understack_workflows/main/undersync_device.py
workflows/argo-events/workflowtemplates/undersync-device.yaml

We now have two separate operations:
1) to set to provisioning mode, the regular nautobot API is used to set the port status
2) to set to tenant mode, a special API call runs Milan's Nautobot job.  This will set the port status as well as creating the relevant VLAN(s).

feat: Neutron ML2 workflow calls nautobot job to set tenant networks

---

components/glance/aio-values.yaml
components/ironic/aio-values.yaml
components/keystone/aio-values.yaml
components/neutron/aio-values.yaml
components/nova/aio-values.yaml
components/placement/aio-values.yaml

Set a minimal Pod Disruption Budget for OpenStack APIs of 1 pod as a starting point.

feat: set minimal PDB for OpenStack APIs

---

apps/aio-app-of-apps.yaml
apps/app-of-apps.yaml
apps/appsets/components.yaml
apps/appsets/infra.yaml
components/ironic/aio-values.yaml
components/ironic/dnsmasq-ss.yaml
components/ironic/kustomization.yaml
components/ironic/understack-data-pvc.yaml
components/openstack/mariadb-instance.yaml
docs/deploy-guide/gitops-install.md
scripts/gitops-secrets-gen.sh

This PR includes various changes required to move us to a multi-node, full K8s cluster that replaced K3s.
Related: https://github.com/RSS-Engineering/undercloud-deploy/pull/148
Closes PUC-518

feat: uc-iad3-dev - redeployment for bravo iteration

---

components/glance/glance-mariadb-db.yaml
components/horizon/horizon-mariadb-db.yaml
components/ironic/ironic-mariadb-db.yaml
components/keystone/keystone-mariadb-db.yaml
components/neutron/neutron-mariadb-db.yaml
components/nova/nova-api-mariadb-db.yaml
components/nova/nova-cell0-mariadb-db.yaml
components/nova/nova-mariadb-db.yaml
components/openstack/mariadb-instance.yaml
components/placement/placement-mariadb-db.yaml
docs/openstack-helm.md
operators/mariadb-operator/kustomization.yaml

The mariadb-operator had a breaking API change. This upgrades to the 0.26.0 CRDs so that we can move to the newer version. This has to be done in increments to handle all the upgrades.

chore: bump mariadb operator to 0.26.0

---

components/ironic/dnsmasq-ss.yaml
python/understack-workflows/understack_workflows/main/undersync_device.py

The undersync expects the port status to be `Provisioning-Interface`, not `Provisioning Interface`. This is also what is created by the Ansible.

fix: undersync interface status was incorrect

---

.pre-commit-config.yaml
docs/component-understack-workflows.md
workflows/argo-events/sensors/nb-oob-interface-update.yaml

The device name parameter was removed so this sensor cannot run the workflow because of the missing field. The sensor could't be updated because of a schema error. I couldn't find where things lived because the documentation wasn't up to date.

fix(workflows): device name param was removed

---

python/understack-workflows/understack_workflows/main/undersync_device.py
python/understack-workflows/understack_workflows/nautobot.py

This is a draft because I need to figure out how to find out the VLAN GROUP for a given Device, I don't know how those two things relate in nautobot
requires: https://github.com/RSS-Engineering/undersync/pull/16
requires: https://github.com/RSS-Engineering/undercloud-nautobot/pull/200

feat: Pass vlan group ID instead of device ID to Undersync

---

python/understack-workflows/tests/conftest.py
python/understack-workflows/tests/test_models.py
python/understack-workflows/tests/test_provision_state_mapper.py
python/understack-workflows/tests/test_sync_bmc_creds.py
python/understack-workflows/tests/test_sync_nautobot_system_info.py
python/understack-workflows/understack_workflows/main/sync_bmc_creds.py

Added few more unit test cases to validate workflows.

chore: create additional test case for testing workflows

---

containers/dnsmasq/dnsmasq/dnsmasq.conf.j2

This minus sign causes us to delete all whitespace prior which creates all the for loop items on the same line creating an invalid config. They need to be on their own line.

fix: do not delete whitespace between dnsmasq options

---

components/ironic/dnsmasq-ss.yaml
containers/dnsmasq/dnsmasq/dnsmasq.conf.j2

Update dnsmasq to have it handle all DNS entries for the entire zone. Ensure that dnsmasq can send ICMP packets.

feat: handle all DNS entries for the entire zone / ensure ICMP packets can work

---

containers/argo_utils/code/argo_python/__init__.py

The owner_name variable refers to a pod name, so that Secret can be automatically cleaned up by kubernetes when the Pod is removed.

fix: argo_python: revert change of owner_name lookup

---

python/understack-workflows/understack_workflows/port_configuration.py

Ironic's database schema requires the baremetal port names to be unique so we prepend the Node ID.

fix: sync_interfaces: make the port names unique

---

containers/argo_utils/code/argo_python/README.md
containers/argo_utils/code/argo_python/__init__.py
docs/component-argo-workflows.md
workflows/argo-events/workflowtemplates/get-bmc-creds.yaml

Instead of relying on a specific environment variable to exist in the context of running this code, require the user to supply the proper ownership information on the call of create_secret().

fix(argo_utils): require the user to supply owner info

---

components/argo/workflow-defaults

5 minutes is not enough for development use cases. If that becomes a scalability problem, we can adjust on a per-environment basis.

chore: argo-workflows: keep the successful workflows for 36 hours

---

components/openstack/mariadb-instance.yaml
operators/mariadb-operator/kustomization.yaml

The CRD changes are able to be done fairly cleanly to this point. After this version they've separated out the CRDs into their own chart and install them differently which will require a bigger effort so let's upgrade to this point.

chore: upgrade mariadb-operator to 0.31.0

---

components/keystone/aio-values.yaml
docs/user-guide/openstack-cli.md

Have users use SSO exclusively for authentication against OpenStack services.

chore: use SSO exclusively for authenticating users

---

.github/workflows/build-container-images.yaml
.github/workflows/build-ironic-images.yaml
.github/workflows/code-test.yaml
.github/workflows/containers.yaml
.github/workflows/mkdocs.yaml
.github/workflows/pr-title-check.yaml
.github/workflows/pre-commit.yml
.github/workflows/typos.yaml
.github/workflows/yamllint.yaml

This is in preparation to enable merge queues.
The `merge_group` trigger is [mandatory](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions) when using [merge queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue)

chore: enable merge_group trigger for GHA

---

python/ironic-understack/ironic_understack/flavor_spec.py
python/ironic-understack/ironic_understack/tests/test_flavor_spec.py
python/ironic-understack/ironic_understack/tests/test_matcher.py

Handle the updates for a singular hardware chassis.

feat(flavor): update for singular hardware chassis

---

components/keystone/aio-values.yaml
docs/user-guide/monitoring.md

Adds some notes around how to access prometheus and alertmanager UIs running inside of the kubernetes cluster. Also adds monitoring user for use with openstack-exporter.

docs: adds additional info for monitoring documentation and adds monitoring user

---

apps/appsets/argocd/appset-argocd.yaml
apps/appsets/components.yaml
apps/appsets/infra.yaml
apps/appsets/openstack.yaml
apps/appsets/operators.yaml
docs/deploy-guide/add-remove-app.md
docs/deploy-guide/auth.md
docs/deploy-guide/extra-regions.md
docs/deploy-guide/gitops-install.md
scripts/gitops-deploy.sh
scripts/gitops-secrets-gen.sh

Flipped the paths in the deploy repo so that the name of the deployment is at the top-level. Renamed secrets to manifests since there is more in there than secrets and folks have complained. Renamed the reference to the deploy repo to deploy from secrets.

chore: flips the deploy paths and rename for clarity

---

docs/deploy-guide/gitops-install.md
scripts/gitops-secrets-gen.sh

Attempt to make the install paths easier to use by sticking to the deploy repo checkout.

docs: make the install paths easier to use

---

apps/appsets/argocd/appset-argocd.yaml
apps/appsets/infra.yaml

These were the changes needed to get the staging environment running.

fix: skippable provisioning-ingress-nginx

---

components/openstack-2024.1-jammy.yaml

We're building our own container. We should use it for more than just the conductor to keep things in sync.

fix(ironic): always use our container for ironic

---

apps/appsets/components.yaml
apps/appsets/infra.yaml
apps/appsets/openstack.yaml
apps/appsets/operators.yaml
docs/deploy-guide/add-remove-app.md

Created a standard on how we should be defining our applications in our AppSets and document it.

chore: standardize and document how AppSets define apps PUC-603

---

bootstrap/argocd/components/sso/kustomization.yaml

This is a public client so has to be separate from the web one.
Related:
https://github.com/RSS-Engineering/undercloud-deploy/pull/195

feat: argocd: configure oauth2 client id for CLI usage

---

docs/schema/flavor.schema.json
python/ironic-understack/ironic_understack/flavor_spec.py
python/ironic-understack/ironic_understack/tests/test_flavor_spec.py
python/ironic-understack/ironic_understack/tests/test_matcher.py
schema/README.md
schema/flavor.schema.json

We'll want to detect and confirm the hardware in Ironic and match it to hardware flavors we want to offer and expect. This schema defines the data files that the flavors hook for Ironic will consume. Changed cpu_models to cpu_model and added support for pci devices list.

feat: flavor schema for ironic hw detect

---

apps/appsets/components.yaml
components/argo/ingress.yaml
components/dex/ingress.yaml
components/glance/aio-values.yaml
components/horizon/aio-values.yaml
components/ironic/aio-values.yaml
components/keystone/aio-values.yaml
components/nautobot/nautobot-values.yaml
components/neutron/aio-values.yaml
components/nova/aio-values.yaml
components/openstack-secrets.tpl.yaml
components/placement/aio-values.yaml
scripts/gitops-secrets-gen.sh

Default all the services to use the 'understack-cluster-issuer' which is documented as the issuer that needs to be provided to create HTTPS entries for everything. This removes the amount of configuration that needs to be done per deployment.

feat: refactor cert-manager issuer for better default

---

.github/renovate.json
.pre-commit-config.yaml
Makefile
apps/appsets/openstack.yaml
workflows/argo-events/docs/README.md

Added a renovate bot rule to watch OpenStack Helm

chore: renovate rule to watch OpenStack Helm

---

python/understack-workflows/pyproject.toml

This seems in the same spirit as the existing rules

chore: Disable ruff checks for missing documentation in classes and __init__

---

components/ironic/ironic-ks-user-baremetal.yaml
components/ironic/kustomization.yaml

The nodes are created in the infra domain under the baremetal project so ensure that the ironic service account has access to that project.

fix(ironic): ensure ironic has access to nodes

---

python/understack-workflows/understack_workflows/main/enroll_server.py
workflows/argo-events/workflowtemplates/enroll-server.yaml

Make the enroll-server script return the device UUID so we can use it for future steps. Then add the process to move the node from enroll to manage and then finally to available.

feat(workflows): enroll-server moves it to available state

---

.github/workflows/containers.yaml

The PR close trigger should clean up our containers and not build them when the PR is closed.

ci: avoid building containers on PR close

---

workflows/argo-events/workflowtemplates/enroll-server.yaml

`input.parameters` section defines the local input parameters, but the container template uses  `"{{workflow.parameters.ip_address}}"` which refers to the global parameter which is already defined [here](https://github.com/rackerlabs/understack/blob/98576ce56dcbd36ae5dd8669e87e27018b34dc51/workflows/argo-events/workflowtemplates/enroll-server.yaml#L12).

fix: enroll-server: remove unnecesary parameter definition

---

containers/ironic/Dockerfile.ironic

Use the latest sushy-oem-idrac which has some fixes around virtual media attachment and handling of jobs.

chore(ironic): bump sushy-oem-idrac for 2024.2

---

apps/appsets/openstack.yaml

Bump glance to 0.5.2 to fix the healthcheck. Bump ironic to 0.2.20 to fix tempdir handling.

feat: bump OSH ironic and glance

---

.github/workflows/containers.yaml

We should be building their containers when things are merged into main and cleaning them up on PRs being closed.

ci: fix to build on containers on main merge

---

python/understack-workflows/understack_workflows/bmc_credentials.py
python/understack-workflows/understack_workflows/main/enroll_server.py

We also get rid of some other unused CLI arguments to reduce confusion
Need to figure out how to use this in the wrokflow

feat: Allow caller to specify current BMC password of baremetal node to enroll

---

.github/workflows/build-ironic-images.yaml
ironic-images/README.md

https://docs.openstack.org/ironic/latest/install/configure-esp.html
https://docs.openstack.org/ironic/latest/install/configure-pxe.html#uefi-pxe-grub

feat: adds github workflow to create an ironic esp image

---

.github/renovate.json
.github/renovate/automergeGitHubActions.json
.github/renovate/default.json
.github/renovate/nautobot.json
.github/renovate/precommit.json

Split up the renovate configs so we can reuse them in some other repos. Enabled auto merging of GitHub Actions minor and patch updates.

chore: update renovate configs for reuse and enable some auto merge

---

.github/workflows/code-test.yaml
.github/workflows/coverage-report.yaml

Make it possible to support forks by splitting the code coverage reporting into two steps. Forks cannot make changes against the main repo so they cannot update the ticket so it must be split into two parts. Simplify the reporting as well by merging it together into one coverage file.

ci: split up code coverage reporting to support forks

---

components/glance/aio-values.yaml

OK, so this is summary of what problem does that solve:
Kubelet executes a liveness probe every 10 seconds to check if Glance is alive, but Glance is not able to respond in time when under load.
This causes the liveness probe to fail, making kubelet ask containerd to stop the container. This is first part of the problem.
The second part of the problem is that upon receiving SIGTERM from kubelet, the uWSGI master process is supposed to gracefully shut down and wait for the ongoing requests to complete, but in reality it sends SIGHUP to the child immediately.
Combination of these two issues results in the image transfers being interrupted.
The first part of the problem partially stems from the fact that each glance-api pod is by default configured to run only a single process, running a …

fix: Corrupted transfers from Glance

---

python/understack-workflows/devbox.json
python/understack-workflows/devbox.lock
python/understack-workflows/pyproject.toml
python/understack-workflows/understack_workflows/main/bmc_display_password.py

This hooks up existing  Steve's script, but also adds another that will automatically retrieve the current value of the BMC master key from the cluster that user is connected to.
Example run:
```
$ devbox run bmc-kube-password 10.4.13.1
lREDACTEDREDACTEDRED
$
```

feat: script to easily display BMC password

---

components/chrony/deployment.yaml
ironic-images/ipa-debian-bookworm.yaml
ironic-images/static/etc/chrony/chrony.conf

The `time.rackspace.net` does not exist anymore, it has to be region specific now. This change also includes fallback to two other NTP pools.
This PR resolves a bug where the booted IPA image did not have the correct time set.
```
root@debian:~# chronyc tracking
Reference ID    : 0A04CC03 (10.4.204.3)
Stratum         : 4
Ref time (UTC)  : Wed Nov 13 12:22:59 2024
System time     : 0.000000373 seconds slow of NTP time
Last offset     : +0.000354720 seconds
RMS offset      : 0.000183107 seconds
Frequency       : 3.873 ppm slow
Residual freq   : +1.198 ppm
Skew            : 1.266 ppm
Root delay      : 0.011129249 seconds
Root dispersion : 0.018068938 seconds
Update interval : 130.0 seconds
Leap status     : Normal
root@debian:~#
```
Closes PUC-413

fix: chrony NTP settings

---

ironic-images/ipa-debian-bookworm.yaml
ironic-images/static/etc/systemd/system/systemd-networkd-wait-online.service.d/justone.conf

This changes behavior of `systemd-networkd-wait-online` so that it does not wait the default 120s for all of interfaces to become online, which in reality never comes effectively delaying boot for 2 minutes.
Instead, we are satisfied with just one interface reaching the IPv4 routable state.
Closes PUC-580

feat: stop waiting for all interfaces to be online in IPA

---

python/understack-workflows/understack_workflows/bmc_chassis_info.py

lldp_info is supposed to contain a dict.  It must not be allowed to be None.

fix: enrollment crash when LLDP info is missing

---

components/nova/aio-values.yaml

The default quotas are too low for bare metal gear to be able to even build one machine so increase the values up.

fix(nova): adjust default quotas higher

---

apps/appsets/openstack.yaml

Fixes:
```
2024-11-14 18:26:57.277 1 ERROR ironic.drivers.modules.ipmitool [None req-80f11e0d-0a17-4f09-a611-dc5b904b5ec2 - - - - - -] Ipmitool drivers need to be able to create temporary files to pass password to ipmitool. Encountered error: Path /var/lib/openstack-helm/tmp does not exist.: ironic.common.exception.PathNotFound: Path /var/lib/openstack-helm/tmp does not exist.
```
Related: 
https://review.opendev.org/c/openstack/openstack-helm/+/935019
https://review.opendev.org/c/openstack/openstack-helm/+/934132

fix: bump ironic chart to 0.2.21

---

python/understack-workflows/tests/test_bmc_chassis_info.py
python/understack-workflows/tests/test_nautobot_device.py
python/understack-workflows/understack_workflows/bmc_chassis_info.py
python/understack-workflows/understack_workflows/bmc_power.py
python/understack-workflows/understack_workflows/discover.py
python/understack-workflows/understack_workflows/helpers.py
python/understack-workflows/understack_workflows/main/enroll_server.py

When the server is powered off the network interfaces are down, so we don't get LLDP information.
Therefore, Enroll should power on the server, then wait for LLDP information to appear before continuing.

feat: Have Enroll power on server and retry fetching LLDP info

---

docs/component-argo-workflows.md
docs/component-overview.md
docs/component-understack-workflows.md
docs/deploy-guide/auth.md
docs/deploy-guide/external-argocd.md
docs/deploy-guide/extra-regions.md
docs/deploy-guide/gitops-install.md
docs/deploy-guide/index.md
docs/vision.md
mkdocs.yml

I also noticed we were pinning the mkdocs github actions to very old versions from March 2024. I've unpinned them.

fix: fixes casing for UnderStack in docs

---

containers/bmc-utils/requirements.txt

The IdracRedfishSupport has been replaced by: https://github.com/rackerlabs/understack/blob/4dea9bb5d9fc71e7e72f5384dd7a91ae44b9b472/python/understack-workflows/understack_workflows/bmc_settings.py#L9-L19

chore: removes unused IdracRedfishSupport python module

---

.github/renovate/default.json
.github/renovate/pythonMinorApprove.json

Many of our dependencies cannot just bump up to the next Python release so we need to get approval to bump up to the next minor release of Python.

chore: renovate should as for minor Python releases

---

bootstrap/argocd/kustomization.yaml

Reverts rackerlabs/understack#438 because of the bug in ArgoCD 2.13.0
https://github.com/argoproj/argo-cd/issues/20171

chore: Revert "chore(deps): update helm release argo-cd to v7.7.3"

---

containers/keystone/Dockerfile.keystone

Prior to this commit we had the Ubuntu mantic APT repository configured just so that we can pull in the libapache2-mod-auth-openidc package. This repository has now been deleted ([deprecated since July 2024](https://wiki.ubuntu.com/Releases)) and we can no longer use it.
This commit changes the Dockerfile to pull the required package directly from [OpenIDC/mod_auth_openidc binary releases](https://github.com/OpenIDC/mod_auth_openidc/releases/tag/v2.4.16.5).

fix: keystone: use prebuilt libapache2-mod-auth-openidc

---

python/understack-workflows/tests/test_nautobot_device.py
python/understack-workflows/understack_workflows/main/undersync_device.py
python/understack-workflows/understack_workflows/nautobot_device.py

The custom fields have been added to ansible, and to the dev and staging environments, and in those environments the data has been copied from the asset_tag field to the new custom field.
We had to change how we do the graphql filter - you could search in Nautobot's built-in string attributes by passing an array of possible values to find, but that doesn't work for custom fields.

fix: Switch from MAC address stored in Nautobot asset_tag to custom field

---

containers/ironic/Dockerfile.ironic

The original intention was to copy both modules into /tmp/ironic-understack/ but the trailing / was missed. Instead, make it more explicit to ensure that both are installed.
Closes #506

fix: ironic image builds without the ironic_understack module

---

apps/appsets/components.yaml
python/understack-flavor-matcher/flavor_matcher/flavor_spec.py

Resource class is coming in to ironic as:
```
| resource_class         | baremetal.gp2.small                                                                                                                                                                 |
```
But it should be `baremetal.gp2small`

fix: fix flavor to ironic resource class conversion

---

python/understack-workflows/understack_workflows/bmc_chassis_info.py
python/understack-workflows/understack_workflows/nautobot_device.py

This improves diagnostic messages during various enroll failure scenarios, to provide a more detailed error message about what went wrong.
It also detects two extra failure cases when DRAC IP is already in use on another device, and when DRAC interface already has an IP address.  This is designed to prevent any "duplicate" IP assignments in Nautobot.
closes PUC-690

feat: Detect and Avoid Duplicate DRAC IP address on server Enroll

---

components/nova/aio-values.yaml

The nova quotas config should be under the nova conf in openstack-helm:
https://github.com/openstack/openstack-helm/blob/master/nova/values.yaml#L1385
https://docs.openstack.org/nova/latest/configuration/sample-config.html
I'm getting this error when I create a new project and try to build a server in the new project:
```
details: 'Quota exceeded for cores, ram: Requested 32, 98304, but already used 0, 0 of 20, 51200 cores, ram'
response: '{"forbidden": {"code": 403, "message": "Quota exceeded for cores, ram: Requested 32, 98304, but already used 0, 0 of 20, 51200 cores, ram"}}'
```
So it's using the 'default' nova quotas and not the ones we were intending to set, and the nova containers do not contain a quota section in /etc/nova/nova.conf.

fix: move nova quota to nova conf section

---

containers/ironic-nautobot-client/Dockerfile.ironic-nautobot-client

psuitl is now a hard dependency for oslo-utils, so we have to build a wheel for it in the builder stage
Closes PUC-692

fix: ironic-nautobot-client: fix container build

---

.github/workflows/build-container-images.yaml
containers/bmc-utils/Dockerfile.bmc_utils
containers/ironic-nautobot-client/Dockerfile.ironic-nautobot-client
containers/python311_alpine/Dockerfile.python311_alpine
containers/python312_alpine/Dockerfile.python312_alpine

Based on the discussion in https://github.com/rackerlabs/understack/pull/499#discussion_r1852786416 this commit removes the repetitive directives to set the application UIDs, GIDs as well as the name and home directory.
The new, standardized way is to use:
- user with name `appuser` and UID 1000
- group with name `appgroup` and GID 1000
- location of the code in `/app`

feat: Hardcode uids in dockerfiles

---

python/neutron-understack/neutron_understack/nautobot.py
python/neutron-understack/neutron_understack/neutron_understack_mech.py

This will create a Nautobot namespace with openstack network ID as a name when create a network in openstack. This is needed when subnets will be created as Nautobot requires namespace for subnets.

feat: Namespace create

---

components/keystone/aio-values.yaml

Problem creating application credentials in keystone: 
```
❯ openstack application credential create terraform-cred --restricted
BadRequestException: 400: Client Error for url: https://keystone.internal/v3/users/b22322eb26e893803f1839640e7de6c9647892c8cffe75b7603f9b168ef1afec/application_credentials, Invalid application credential: Could not find role assignment with role: 4a5321ded95d4c2caa3ebb329fd12dd5, user or group: b22322eb26e893803f1839640e7de6c9647892c8cffe75b7603f9b168ef1afec, project, domain, or system: 9c5848c68f1c41d181365eea45ed804b.
```
I came across some keystone bug reports:
* https://bugs.launchpad.net/keystone/+bug/1978833 
* https://bugs.launchpad.net/keystone/+bug/1832092 
Which led to the same solution, setting default_authorization_ttl to something greater than 0 …

fix: set keystone federation default_authorization_ttl to 12 hours

---

workflows/argo-events/workflowtemplates/keystone-event-project.yaml

I noticed my test tenants aren't getting deleted in nautobot when I delete them in keystone. Upon investigating, I found the argo event is failing with an error regarding the service account: 
```
Error (exit code 1): pods "keystone-event-project-mtl4s" is forbidden: User "system:serviceaccount:argo-events:default" cannot patch resource "pods" in API group "" in the namespace "argo-events"
```
I believe the default user is old.. it's mentioned in https://github.com/rackerlabs/understack/blob/main/components/argo-events/default-role.yaml  but this file seems unused. The other workflows are using a `workflow` user, so I set this keystone workflow to the same, and the argo events are successfully completing now, and the projects are getting deleted in nautobot as expected.

fix: adds service account to keystone argo event source

---

apps/appsets/openstack.yaml

This includes fixes from
https://review.opendev.org/c/openstack/openstack-helm/+/936258
Closes PUC-633

chore:  bump nova chart to 0.3.47

---

components/nautobot/values.yaml

We don't use this anymore now that we have the upstreamed group_sync.

fix(nautobot): remove unused dexauth mount

---

operators/nova-flavors/nova_flavors/flavor_synchronizer.py
operators/nova-flavors/tests/test_flavor_synchronizer.py
python/understack-flavor-matcher/flavor_matcher/flavor_spec.py
python/understack-flavor-matcher/tests/test_flavor_spec.py
python/understack-workflows/understack_workflows/flavor_detect.py
workflows/argo-events/workflowtemplates/enroll-server.yaml

We don't want to be prefixing the flavor names with an environment name. Just put the environment data in the correct place.

fix: we don't want the env name in the flavor

---

operators/monitoring/values.yaml

The kube-prometheus-stack includes a number of default alerts, including one for kube-proxy. We don't have kube-proxy as we're using cilium, so the alert continually fires. This disables the kube-proxy default monitoring.

fix: update kube-prometheus-stack default alerts to not include kube-proxy

---

docs/user-guide/nautobot.md
mkdocs.yml

Adds a new page in the user guide section for Nautobot.

docs: adds some nautobot docs and examples

---

python/ironic-understack/ironic_understack/redfish_inspect_understack.py
python/ironic-understack/ironic_understack/resource_class.py
python/ironic-understack/pyproject.toml
python/neutron-understack/neutron_understack/neutron_understack_mech.py
python/neutron-understack/neutron_understack/tests/test_neutron_understack_mech.py
python/neutron-understack/pyproject.toml
python/understack-flavor-matcher/flavor_matcher/flavor_spec.py
python/understack-flavor-matcher/flavor_matcher/matcher.py
python/understack-flavor-matcher/pyproject.toml
python/understack-flavor-matcher/tests/test_flavor_spec.py
python/understack-flavor-matcher/tests/test_matcher.py
python/understack-workflows/pyproject.toml

Get all of our Python projects in sync with regards to ruff linting rules.

chore: get ruff linting in sync between all projects

---

python/understack-workflows/understack_workflows/ironic/provision_state_mapper.py

Nautobot status 'Decom' doesn't exist but 'Decommissioning' does. Switches to the correct status.

fix: Nautobot status 'Decom' doesn't exist; switch to Decommissioning

---

docs/deploy-guide/deploy-repo.md
docs/deploy-guide/getting-started.md
docs/deploy-guide/index.md
mkdocs.yml

Start to break up the docs from the quick start into each component step so that it's more clear how things are intended to be deployed.

docs: start to break up and define the deployment

---

containers/nova-flavors/Dockerfile.nova-flavors

This PR addresses a build failure after new version of the `psutil` has been released. The psutil required by dependencies is 6.1.0 and the builder stage used to deliver the latest which is now 6.1.1.
This PR also fixes the PIP cache directory which is `~/.cache/pip`and not `~/.cache/.pip`.
https://pip.pypa.io/en/stable/topics/caching/#default-paths

fix: nova-flavors: resolve the container build problem

---

python/understack-workflows/tests/conftest.py
python/understack-workflows/understack_workflows/main/sync_keystone.py

Nautobot has integrated the idempotent IDs feature so switch to that instead of using our custom piece.

feat(workflows): switch to nautobot native idempotent IDs

---

examples/tf-multi-node-build/main.tf

Terraform was issuing creation of the server before the subnt was fully created, causing an error. Notice the server gets created before subnet:
```
openstack_networking_network_v2.tenant_net: Creating...
openstack_compute_keypair_v2.ssh_keypair: Creating...
openstack_compute_keypair_v2.ssh_keypair: Creation complete after 1s [id=ringtail]
openstack_networking_network_v2.tenant_net: Creation complete after 7s [id=3d1a58d9-f869-4a81-b4a3-4d9a5ceec578]
openstack_compute_instance_v2.tenant_server[1]: Creating...
openstack_compute_instance_v2.tenant_server[0]: Creating...
openstack_networking_subnet_v2.tenant_subnet: Creating...
openstack_networking_subnet_v2.tenant_subnet: Creation complete after 6s [id=fbf46959-cea2-48e5-aa08-f3e3ec58194e]
openstack_compute_instance_v2.tenant_server[1]: …
```

fix: ensure prerequisite resources are created before we create a server

---

components/neutron/aio-values.yaml

The segments plugin is for routed L3 networks which we aren't using and don't have an intention to use at this time. But we do want to allow OpenStack to select our VLAN and VNIs for our fabric but we don't want this in a config file so enable the API extension to let us manage this directly.

feat(neutron): enable network segment range but disable segments plugin

---

containers/dnsmasq/Dockerfile.dnsmasq
containers/dnsmasq/dnsmasq/dhcp-allowed-srvids.patch

Debian bumped to 2.90 and dropped the version of python-jinja2 so update things to be a bit more dynamic for bumps. Rebased our patch onto 2.90. Fixed an issue where the Debian patches were dropped for our patch. Changed to appending ".uc1" to the Debian version to make it more clear as to the version origin if you hop into the container.

fix(dnsmasq): rebased to 2.90 for Debian bump

---

components/neutron/aio-values.yaml
python/neutron-understack/neutron_understack/neutron_understack_mech.py
python/neutron-understack/neutron_understack/trunk.py

Enables the trunk plugin so that we can create trunk ports. This provides a stub interface for our understack ML2 driver so that it can load.

feat(neutron): enable trunk plugin

---

components/keystone/aio-values.yaml

I believe we've hit an old issue described here: https://bugs.launchpad.net/keystone/+bug/1901124

fix: update keystone memcached cache settings

---

docs/user-guide/openstack-image.md

So that we can see the progress of the image upload since large images can take a while to complete.

docs: adds --progress option when creating an OpenStack image

---

python/understack-workflows/understack_workflows/main/undersync_device.py
python/understack-workflows/understack_workflows/main/undersync_switch.py
python/understack-workflows/understack_workflows/undersync/client.py
workflows/argo-events/workflowtemplates/undersync-switch.yaml

A long time ago this workflow used to take a switch ID argument.  This was changed to a Vlan Group ID argument, but I was lazy and failed to update identifiers and parameter strings to reflect the change in behaviour.  This PR cleans up the confusment.
closes PUC-732

fix: rename workflow parameters

---

components/nova/aio-values.yaml

We've hit an upstream OpenStack Nova bug with the ironic driver:
https://bugs.launchpad.net/nova/+bug/2019977
https://review.opendev.org/c/openstack/nova/+/883411
A work around is to increase the retries and retry interval for the ironic driver in order to get a longer timeout period, in order to wait until the ironic node cleaning has completed and ironic unlocks the node.

fix: update nova's ironic retry settings to allow for node cleaning time

---

components/keystone/aio-values.yaml

Pulls in the upstream change from: https://review.opendev.org/c/openstack/openstack-helm/+/934703 which is currently pending review process. Once that gets merged in to the upstream values, we can remove it from this override.

fix: fix keystone max active fernet keys

---

components/keystone/aio-values.yaml
components/nautobot/cloudnative-postgres-nautobot.yaml
components/nautobot/values.yaml
components/openstack/mariadb-instance.yaml
operators/cnpg-system/values.yaml
operators/external-secrets/kustomization.yaml
operators/external-secrets/values.yaml
operators/mariadb-operator/values.yaml
operators/monitoring/values.yaml
operators/rook/values-operator.yaml

We have the prometheus operator already in place. This enables the helm chart option to set up prometheus metrics+monitoring for charts where that feature exists.

feat: enables monitoring and metrics in helm charts

---

examples/tf-multi-node-build/main.tf
examples/tf-multi-node-router/.gitignore
examples/tf-multi-node-router/README.md
examples/tf-multi-node-router/main.tf
examples/tf-multi-node-router/variables.tf
examples/tf-multi-node-router/versions.tf

Adds the creation of an OpenStack router and floating IP address that gets assigned to the first server that is built.

feat(examples): add router and floating IP to terraform

---

docs/operator-guide/openstack-ironic.md

docs(ironic): adds link to upstream page for baremetal node history docs

docs(ironic): adds link to upstream page for baremetal node history docs

---

workflows/argo-events/workflowtemplates/enroll-server.yaml

The node needs to be in `manageable` status before we can perform the raid cleaning.

fix: update enroll workflow to put node in manageable status before cleaning it

---

python/neutron-understack/neutron_understack/config.py
python/neutron-understack/neutron_understack/nautobot.py
python/neutron-understack/neutron_understack/neutron_understack_mech.py
python/neutron-understack/neutron_understack/vlan_manager.py

This PR modifies the Understack mechanism driver by hooking `create_network_precommit` event to verify if the selected VLAN ID is available in particular fabric before assigning it.
That feature heavily relies on the Nautobot data being correct. The concept of availability is abstracted away through custom API plugin in Nautobot which returns simple 'true/false'.
For the input, we take the `interface_id` which is configured statically in Neutron's configuration as `network_node_switchport_uuid`. This refers to an interface of a "network node" which presumably is always the first interface to be hooked into the network.
The second input is a `vlan_tag` as chosen by the Neutron.
If Nautobot considers the vlan to be available, the hook returns and the allocation proceeds as normal. If it …

feat: Neutron: consistent vlan assignments 

---

components/nautobot/nautobot_config.py
python/neutron-understack/neutron_understack/nautobot.py
python/neutron-understack/neutron_understack/neutron_understack_mech.py

This allows the ML2 to operate both in VLAN and VXLAN environments.
related: https://github.com/RSS-Engineering/undercloud-rackspace/pull/344

feat: understack mech: configurable VXLAN/VLAN operation

---

docs/operator-guide/rabbitmq.md

The echo adds newlines to make it easier to see the output when copy/pasting from the docs.

docs: make output easier to read and copy/paste

---

bootstrap/argocd/values.yaml

Instead of giving the blanket admin permissions to the ucadmin, dial back to a more limited default.

feat(argocd): set some less privileged RBAC rules

---

python/understack-workflows/understack_workflows/ironic/provision_state_mapper.py

Fix for an ironic-node-update error I saw in argo workflows:
``` text
2025-02-06 20:27:27 +0000 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): nautobot-default.nautobot.svc.cluster.local:80
2025-02-06 20:27:27 +0000 - urllib3.connectionpool - DEBUG - http://nautobot-default.nautobot.svc.cluster.local:80 "GET /api/ HTTP/1.1" 200 977
Traceback (most recent call last):
File "/opt/venv/bin/sync-provision-state", line 8, in <module>
sys.exit(main())
^^^^^^
File "/opt/venv/lib/python3.11/site-packages/understack_workflows/main/sync_provision_state.py", line 60, in main
do_action(
File "/opt/venv/lib/python3.11/site-packages/understack_workflows/main/sync_provision_state.py", line 38, in do_action
new_status = ProvisionStateMapper.translate_to_nautobot(provision_state) …
```

fix: adds 'clean failed' ironic provision state

---

components/neutron/aio-values.yaml

OpenStack Helm hardcodes a default VNI range of 1:1000 which causes that range to always be available. We're using the network-segment-range service plugin and want to always configure our ranges with that.

fix(neutron): don't default VNIs

---

components/keystone/values.yaml
scripts/gitops-secrets-gen.sh
scripts/pwgen.sh

Problem: 
Unable to authenticate when the user receives the initial state, it is encrypted with a key from pod A, then user is redirected to the identity provided and finally when they get back through redirect, they may land on pod B which is no longer able to decrypt the state.
Solution:
OIDCCryptoPassphrase is a password used for encryption of the state cookie and cache entries and it must be the same on all replicas.
Previously we were setting the OIDCCryptoPassphrase to a random value that is generated on pod startup and multiple pods have different value.

feat: PUC-752: reading OIDCCryptoPassphrase from a file

---

python/neutron-understack/devbox.json
python/neutron-understack/devbox.lock
python/neutron-understack/neutron_understack/nautobot.py
python/neutron-understack/neutron_understack/neutron_understack_mech.py
python/neutron-understack/neutron_understack/tests/test_neutron_understack_mech.py
python/understack-workflows/devbox.json
python/understack-workflows/devbox.lock

This PR has the required ml2 driver changes.  Note that this
represents a change to the meaning of the Nautotbot data.
UCVNI->Prefic to a one-to-many relationship
We currently represent SVIs explicitly in Nautobot:
- we have an IpAddress object with the SVI address (.1)
- for each leaf Device, we have an Interface named "Vlan{vlan_id}"
- we associate the IpAddress with each Interface
- Interface.role is used to select the SVI configuration template
We simplify this by leveraging the direct relationship between VNI and Prefix.
Using the existing Prefix->VNI mapping is a natural way to model the SVI.
- For VLANs which have a prefix, via Vlan->UCVNI->Prefix
- SVI is implicitly created wherever we create the VLAN
- bake in assumption that the SVI has .1 IP Address
- specify the template to …

feat: Create SVIs on leaf switches using a Network with a router-external Subnet 

---

components/neutron/values.yaml
python/neutron-understack/neutron_understack/config.py
python/neutron-understack/neutron_understack/neutron_understack_mech.py

We won't ever support gre and flat networks so drop those out right. local is really for testing as a no-op so remove that as well but it might find its way back in for test purposes later. Fixed incorrect usage of pass. Handle old and new config file location.

chore(neutron): drop unused net types and use new config

---

python/neutron-understack/neutron_understack/nautobot.py
python/neutron-understack/neutron_understack/vlan_manager.py

- make sure exceptions have useful "message"
- consider HTTP redirect responses to be errors
- include URL and payload in exceptions on failed API request
- remove default params (all our callers pass all the args)
- don't log errors, just raise the exception
- re-order args to make_api_request to match the requests library
- combine api request and response into single log message
- pretty-print payload data when logging Nautobot API requests

fix: Refactor Nautobot api client and update logging / exception handling

---

components/openstack/mariadb-instance.yaml

Adds backups for the openstack mariadb database: https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/BACKUP.md
To restore, we can use the 'target recovery time' functionality: https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/BACKUP.md/#target-recovery-time

feat: Adds mariadb-operator backups for OpenStack services

---

components/neutron/kustomization.yaml
components/neutron/neutron-nautobot.yaml
components/neutron/values.yaml
python/neutron-understack/neutron_understack/config.py

The config option parser was not requiring the nautobot auth info which was no longer defaulted or read from the existing location as of #666. This makes it required for the server to start up successfully. Lastly the auth information was actually being read from a location supplied by the workflows so create a new secret with the data populated. Create the secret in the syntax of a config snippet for oslo.config to automatically pick up for us and load in.

fix(neutron): require nautobot auth and provide it by default

---

apps/appsets/components.yaml
apps/appsets/infra.yaml
apps/appsets/operators.yaml

In e22cccdba9c3557 we made the change only for OpenStack components but this brings it to the rest.
See:
https://argo-cd.readthedocs.io/en/stable/user-guide/diff-strategies/ https://github.com/argoproj/argo-cd/issues/11143

fix: finish working around ArgoCD ServerSideApply

---

components/openstack/mariadb-instance.yaml

Adjusts the settings for backups. Users can override these settings if they need. Reducing volume and retention of backups will help in our smaller dev environments where I had just hit some disk space issues.

fix: tune openstack db backup settings

---

components/neutron/values.yaml
docs/deploy-guide/override-openstack-svc-config.md
mkdocs.yml

Due to https://bugs.launchpad.net/oslo.config/+bug/2098514 the path for the config file snippet that was originally used can change and we don't want that. So change paths and document why this is. Added a document explaining how you can provide further extensions for your deployment as well. Dropped the rpc-server section since we've got that disabled always now.

feat(neutron): fix config paths for different startup case and drop rpc-server config

---

components/horizon/values.yaml

Set config drive option to enabled by default when building a new server in the Horizon dashboard.

feat(horizon): Set default instance launch settings to include config drive

---

components/ironic/values.yaml

the service account belongs to the service project but our nodes will live in the infra domain in the baremetal project so the service account needs to have permissions outside of just the service project
see: https://review.opendev.org/c/openstack/ironic/+/907148

fix(ironic): adjust ironic service account permissions

---

python/neutron-understack/neutron_understack/nautobot.py
python/neutron-understack/neutron_understack/tests/test_trunk.py
python/neutron-understack/neutron_understack/trunk.py
python/neutron-understack/neutron_understack/utils.py

This PR will enable us to set "tenant_vlan_id" on UCVNI in Nautobot when first subport is added to neutron trunk and user specifies the "segmentation_id" when adding the subport. The idea is that we will use the "tenant_vlan_id" as mapped VLAN that is local to the switchport during server provisioning. 
This PR covers only the trunk driver part and there will be another one where we will adjust the understack mechanism driver, so when server will go through provisioning, we will detect the trunk_details on the port attached and do the needful to configure our network.

feat: understack trunk

---

components/ironic/values.yaml

Issues we're seeing:
``` text
{'code': 500, 'created': '2025-01-23T15:24:50Z', 'message': 'Build of instance
953691fd-1dde-4b01-9010-e0d45d1a9dfa aborted: Failed to provision instance
953691fd-1dde-4b01-9010-e0d45d1a9dfa: ** Value Redacted - Requires
baremetal:node:get:last_error permission. **'}
```

fix(ironic): allow lessee to see the last error in a build

---

.github/workflows/containers.yaml
.typos.toml
containers/nova/Dockerfile.nova
containers/nova/patches/0001-ironic-fix-logging-of-validation-errors.patch
containers/nova/patches/0001_trunk_details_metadata.patch
containers/nova/patches/series

Add patches to fix:
- ironic node validate error message log
- metadata trunk_details added

feat(nova): build our own container with patches

---

components/neutron/values.yaml
components/ovn/values.yaml
python/neutron-understack/neutron_understack/type_understack_vxlan.py

Instead of standing in for the VXLAN type driver directly, have it be its own thing that will be ignored by mechanisms that consume it. The reason is that the existing VXLAN type driver is treated and consumed as a L3VNI while we need L2VNI.

feat(neutron): make our VXLAN type driver unique

---

python/neutron-understack/neutron_understack/nautobot.py

Logs more information, but limits the size of any raw payloads we dump out to the logger.
Also extracts the "error" key instead of logging the whole json payload.
```
neutron_understack.nautobot.NautobotRequestError: Nautobot API ERROR 404 for https://nautobot.dev.undercloud.rackspace.net/testing-failures POST {'payload1': 123}: {'body': 'b\'\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang="en">\\n<head>\\n    '
'<title>Page Not Found - Nautobot</title>\\n    \\n\\n\\n\\n    <link '
'rel="stylesheet" id="template-theme"\\n          '
'href="/template.css">\\n    <lin...10971 more chars'}
```

fix: Further updates to Nautobot api response logging

---

python/understack-workflows/understack_workflows/main/sync_provision_state.py

The code doesn't have mappings for all the possible ironic states. If we hit an ironic state with no mapping, the result is an exception:
```
kubectl logs -f ironic-node-update-28fgn
2025-02-19 14:23:54 +0000 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): nautobot-default.nautobot.svc.cluster.local:80
2025-02-19 14:23:54 +0000 - urllib3.connectionpool - DEBUG - http://nautobot-default.nautobot.svc.cluster.local:80 "GET /api/ HTTP/1.1" 200 977
2025-02-19 14:23:55 +0000 - urllib3.connectionpool - DEBUG - http://nautobot-default.nautobot.svc.cluster.local:80 "GET /api/dcim/devices/6cc75fc1-756a-4b19-bbab-fe8e63eee45b/ HTTP/1.1" 200 2243
2025-02-19 14:23:55 +0000 - urllib3.connectionpool - DEBUG - http://nautobot-default.nautobot.svc.cluster.local:80 "PATCH …
```

fix(understack-workflows): don't try to set nautobot status if it doesn't exist

---

.github/renovate.json

This disables recently added renovate package manager. We generally don't want to have this automatically updated because whole point of creating an isolated dev environment is to have the ability to pin specific versions of the dependencies without affecting anyone else.
ref: 
https://github.com/renovatebot/renovate/issues/27543
https://github.com/jetify-com/devbox/pull/2508

fix: renovate: disable devbox package manager

---

python/understack-workflows/understack_workflows/main/sync_keystone.py

This can only be done by admin, so we take care of it here.
Closes PUC-764

feat: Create an OUTSIDE Network in Neutron for each new project (tenant)

---

python/neutron-understack/neutron_understack/neutron_understack_mech.py
python/neutron-understack/neutron_understack/tests/test_neutron_understack_mech.py

Reverts rackerlabs/understack#721 because we cannot build servers on a Subnet that has a service_type set:
neutronclient.common.exceptions.Conflict: No valid service subnet for the given device owner, network 1499b961-2f5a-494a-b35a-bad9d727b74f, service type .
The [docs](https://docs.openstack.org/neutron/latest/admin/config-service-subnets.html) say that  the service type should be "matching the port device owner" which suggests to me that maybe we should not be using that field at all for this purpose, since we don't control the port device owner?

fix: Revert "feat: Only create SVIs for Prefixes of service_type "network:understack_svi""

---

python/understack-workflows/understack_workflows/main/sync_keystone.py

The API accepts the project_id value verbaitm, we want the plain hex format as used by the rest of openstack, not a normal UUID.

fix: Specify project_id without dashes, as per openstack legacy convention

---

apps/appsets/argocd-operators-project.yaml
apps/appsets/components.yaml
apps/appsets/operators.yaml
operators/opentelemetry-operator/cert-manager-issuer.yaml
operators/opentelemetry-operator/kustomization.yaml
operators/opentelemetry-operator/values.yaml

Adds opentelemetry operator and a component for the collector

feat: Added opentelemetry-operator and otel-collector component

---

python/understack-workflows/understack_workflows/main/sync_keystone.py

Without this "shared" rule, the instance failed to build with:
nova.exception.ExternalNetworkAttachForbidden: It is not allowed to create an interface on external network <uuid>
We make the network shared, but only to this single project, so it remains invisible to other tenants.

fix: Create second rbac policy on OUTSIDE network to permit "shared" access

---

components/neutron/values.yaml
docs/component-networking-neutron.md
mkdocs.yml

We're working with bare metal switches and not OpenFlow in OVS so we don't have the ability right now to use security groups universally without specific switch support. We're also wanting a maximum of 9000 MTU advertised so we need to set it to 9050 to account for Neutron's VXLAN math.

feat(neutron): set some neutron defaults

---

apps/appsets/operators.yaml
operators/rook/values-cluster.yaml

This fixes https://github.com/rook/rook/issues/13904 which is needed for @haseebsyed12's [work on PUC-523](https://github.com/rackerlabs/understack/tree/puc-523_glance-ceph-radosgw-backend).
Bravo cluster has been updated to 16.4 now.

chore: Rook upgrade to 16.4

---

bootstrap/argocd/values.yaml

This configures ArgoCD to exclude the CiliumIdentity objects from sync process. Without this, we have a false reports on applications being out of sync. Moreover, we suspect that if ArgoCD forces removal of those objects it may impact the network connections from affected namespaces.

fix: ArgoCD -  exclude CiliumIdentity from sync

---

components/neutron/values.yaml

Our networks are based on L2VNI so we need to have this defaulting to vxlan.

feat(neutron): set default tenant network to vxlan

---

apps/appsets/operators.yaml
operators/monitoring/values.yaml

ArgoCD is fighting the prometheus operator and needs to have the correct annotations set on it to avoid this.
see: https://github.com/prometheus-community/helm-charts/issues/4500#issuecomment-2693911587

fix: avoid prometheus operator fighting ArgoCD

---

python/neutron-understack/neutron_understack/neutron_understack_mech.py
python/neutron-understack/neutron_understack/tests/conftest.py
python/neutron-understack/neutron_understack/tests/test_neutron_understack_mech.py

Currently, when any update is made to the neutron port where vif-type is "other", it triggers the whole logic in update_port_postcommit which is meant to be only on the bind port, so in other words, when baremetal port is attached to the server being kicked, we only need to trigger it once to setup switchport config. The best place for this logic therefor is bind_port.

fix: move logic from update_port_postcommit 

---

ironic-images/requirements.txt

Updates the ironic-python-agent-builder to the latest version which includes this fix: https://review.opendev.org/c/openstack/ironic-python-agent-builder/+/943334 for the missing hexdump command.

chore: Bump ironic-python-agent-builder version to resolve missing hexdump issue

---

python/neutron-understack/neutron_understack/neutron_understack_mech.py

If a port has IP address then port binding won't happen by default. We have the same requirements of https://launchpad.net/bugs/2097803 so we need the same behavior.

fix(neutron): ensure we bind on L2 only ports

---

docs/operator-guide/mariadb-operator.md

docs: Adds operator docs on restoring mariadb-operator backups

docs: Adds operator docs on restoring mariadb-operator backups

---

components/ironic/dnsmasq-ss.yaml
components/ironic/kustomization.yaml

This configmap needs to be custom for each deployment so we shouldn't ship this by default. As a result mark it optional until the user defines one.

chore(ironic): don't ship default ironic-dnsmasq configmap

---

workflows/openstack/eventsources/eventsource-openstack-ironic.yaml
workflows/openstack/eventsources/eventsource-openstack-keystone.yaml
workflows/openstack/eventsources/rabbitmq-user-argo-ironic.yaml
workflows/openstack/eventsources/rabbitmq-user-argo-keystone.yaml
workflows/openstack/eventsources/rabbitmq-user-argo.yaml
workflows/openstack/kustomization.yaml

Added two distinct users for argo events to connect to two rabbitmq vhosts since we've seen an issue with the operator not ensuring the same user has access to both vhosts before.

chore(workflows): distinct users for argo events

---

components/openstack/mariadb-instance.yaml

The server side diff pieces aren't necessary as we've updated the ArgoCD configurations for this. We also had the wrong identification of the container image for renovate. Switched to the officially documented supported mariadb image by the operator.
https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/DOCKER.md

chore(mariadb): update instance info

---

apps/appsets/understack.yaml

fix: understack-infra appset needs to install to kube-system

---

components/nautobot/kustomization.yaml

superusers in Nautobot ignore permissions and have access to everything. This is likely not something you want on by default. But the staff group has the ability to make changes so this can be the escape hatch to let people elevate their permissions should they need.

fix(nautobot): no superusers by default

---

python/diff-nautobot-understack/diff_nautobot_understack/cli.py
python/diff-nautobot-understack/diff_nautobot_understack/project/adapters/nautobot_tenant.py
python/diff-nautobot-understack/diff_nautobot_understack/project/adapters/openstack_project.py
python/diff-nautobot-understack/diff_nautobot_understack/project/main.py

Adds a new command: `uc-diff projects` to show the differences for all the OpenStack projects versus Nautobot tenants.

feat: Adds 'uc-diff projects' to diff all projects

---

apps/appsets/understack.yaml

To deploy a cert-manager webhook we need to be able to create a rolebinding in kube-system so access must be granted here.

fix(argocd): deploying cert-manager webhooks requires kube-system

---

operators/monitoring/values.yaml

The comments in the default values.yaml are wrong for the helm chart for this and one of the maintainers pointed out the correct values at: https://github.com/prometheus-community/helm-charts/issues/4500#issuecomment-2724199565

fix(prometheus): prevent constant sync cycling with ArgoCD

---

components/glance/values.yaml

Due to the way OpenStack Helm loads their jobs and requires jobs to exist forever and that jobs are immutable, we need to have ArgoCD delete the existing or replace them when it runs a sync to apply any changes otherwise we hit immutable errors.

fix(glance): add job annotations to fix sync issues

---

python/neutron-understack/neutron_understack/nautobot.py
python/neutron-understack/neutron_understack/neutron_understack_mech.py
python/neutron-understack/neutron_understack/tests/conftest.py
python/neutron-understack/neutron_understack/tests/test_nautobot.py
python/neutron-understack/neutron_understack/tests/test_neutron_understack_mech.py

Reason for code clean up related to VLAN type networks is,  we were experimenting with VLAN type networks but we switched back to VXLAN networks and in future also we want to use VXLAN type networks only.

feat: PUC-765: use segmentation_id generated by neutron as ucvni_id in nautobot

---

components/keystone/values.yaml

The way OpenStack Helm does their job configuration is incompatible with how Kubernetes treats jobs. So we must set annotations to have ArgoCD delete the job before applying any updates to the job.

fix(keystone): add job annotations for syncing

---

python/understack-workflows/understack_workflows/bmc_bios.py
python/understack-workflows/understack_workflows/discover.py

This makes enroll work on the prod node iDRACs

fix: change bios settings for enroll, and add more LLDP details on missing neighbors

---

components/glance/values.yaml

When attempting to upload a new image, glance-api crashes with this error:
``` text
2025-03-28 15:42:33.305 22 INFO glance.api.v2.image_data [None req-6e15a68a-b57c-48bb-8679-770e67eb16bd 7129b5909a1d44c394fc84d915aa1e8d 2ae532bb8a82466ebba66c7a9a806eb5 - - default default] Unable to create trust: no such option collect_timing in group [keystone_authtoken] Use the existing user token.
DAMN ! worker 2 (pid: 22) died, killed by signal 9 :( trying respawn ...
Respawned uWSGI worker 2 (new pid: 30)
```

fix(glance): Increase memory limits due to errors uploading images

---

python/understack-workflows/understack_workflows/nautobot_device.py

Follow the Ironic/Nautobot state mapping by enrolling servers into Nautobot at the Planned state instead of creating a new state called "enroll" inside of Nautobot.

fix(workflows): enrolling servers in Nautobot as Planned

---

python/neutron-understack/neutron_understack/nautobot.py
python/neutron-understack/neutron_understack/neutron_understack_mech.py
python/neutron-understack/neutron_understack/tests/test_neutron_understack_mech.py

The Nautobot update is supposed to be adding to the set of subnets that are associated with the UCVNI.  It was incorrectly replacing the entire set.
With these changes, the network/UCVNI gets correctly associated with both subnets/prefixes:
and the correct configuration ends up on the switch:
```
interface Vlan1100
description 1100_OUTSIDE___cccbb055
no shutdown
ip access-group customer-12200-CUSTOM in
vrf member PUBLIC
no ip redirects
ip address 10.4.88.33/28 tag 50000
ip address 10.4.88.49/28 secondary tag 50000
no ipv6 redirects
fabric forwarding mode anycast-gateway
```

fix: secondary IP blocks on "external" subnets (SVIs)

---

apps/appsets/openstack.yaml

https://tarballs.opendev.org/openstack/openstack-helm/

chore: Bump openstack-helm nova version to the latest

---

components/nautobot/cloudnative-postgres-nautobot.yaml
components/nautobot/values.yaml
components/openstack/mariadb-instance.yaml
components/openstack/memcached-values.yaml
components/openstack/openstack-cluster.yaml

This ensures that these resources are not deleted automatically through a sync operation. This should really be an intentional operation to delete them.

chore: protect resources from automated deletion

---

python/understack-workflows/pyproject.toml
python/understack-workflows/tests/test_sync_ucvni_group_range.py
python/understack-workflows/understack_workflows/main/sync_ucvni_group_range.py
workflows/argo-events/workflowtemplates/neutron-event-network-segment-range.yaml
workflows/openstack/eventsources/eventsource-k8s-openstack-neutron.yaml
workflows/openstack/eventsources/eventsource-openstack-neutron.yaml
workflows/openstack/eventsources/rabbitmq-user-argo-neutron.yaml
workflows/openstack/kustomization.yaml
workflows/openstack/sensors/sensor-k8s-neutron-deployment.yaml
workflows/openstack/sensors/sensor-neutron-event-network-segment-range.yaml
workflows/openstack/serviceaccounts/serviceaccount-k8s-openstack-events.yaml

[tested end to end workflow](https://workflows.dev.undercloud.rackspace.net/workflows/argo-events/neutron-event-network-segment-range-hkbsv?tab=workflow&nodeId=neutron-event-network-segment-range-hkbsv&uid=0e7a2484-6a1c-4e3c-b824-9a68fa40bdfe)

feat: PUC-785: crud ucvni-group range on network-segment-range events

---

apps/appsets/project-understack.yaml
apps/appsets/understack.yaml

The componentProject was not set for the otel-collector and it was trying to be installed under the nonexistent otel-collector project.

fix: the otel-collector should be in the understack project

---

components/nova/values.yaml

OpenStack Helm contains a list of hardcoded flavors, which can be further extended but is limited in that properties cannot be set which is a must for Ironic support so this is not useful to us so disable it entirely.

chore(nova): we never use the OSH hardcoded flavors so disable them

---

python/neutron-understack/neutron_understack/nautobot.py
python/neutron-understack/neutron_understack/neutron_understack_mech.py
python/neutron-understack/neutron_understack/tests/test_utils.py
python/neutron-understack/neutron_understack/trunk.py
python/neutron-understack/neutron_understack/utils.py

We wanted this to become a name rather than a nautobot UUID.  To support the transition from UUID to interface name, we accept a value of either kind.  If the value is not a UUID, we look it up in nautobot.

feat: Accept either name or UUID for switch interface in local_link_info

---

python/neutron-understack/neutron_understack/ml2_type_annotations.py
python/neutron-understack/neutron_understack/neutron_understack_mech.py

Hacking on the ml2 driver plugin feels very uncertain due to the large number of inter-dependencies that the driver code has, and the poorly-documented API with confusing concepts, like the "context" argument means different things in different places.
I don't know if this is a valid approach to documenting the API, but adding type hints or comprehensive documentation upstream seems unlikely to be a quick or easy win, while this gets a bit of autocomplete working with minimal effort.  While these type hints will surely get out of date, I assume that the ml2 API would be evolving quite slowly, so we won't see too much drift.

chore: Retrofit type hints to neutron ml2 driver plugin API to improve dx

---

apps/appsets/appset-understack-infra.yaml
apps/appsets/appset-understack-operators.yaml
apps/appsets/components.yaml
apps/appsets/openstack.yaml
apps/appsets/understack.yaml

We should not be setting this finalizer on our Applications since it should be set there by the AppSet applicationsSync. See https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/ for more context.

fix(argocd): remove finalizer that should by controlled by policy

---

apps/appsets/project-understack-infra.yaml
apps/appsets/project-understack-operators.yaml
apps/appsets/project-understack.yaml

Reverts the finalizer added on AppProjects in 04d352154effaa as this causes all resources to be deleted when they transition between AppProjects despite any other settings.

fix(argocd): revert finalizer on appproject

---

python/understack-workflows/tests/test_sync_interfaces.py
python/understack-workflows/understack_workflows/sync_interfaces.py

Groundwork was laid in #842 and #845 which have both been merged
The old requirement to use UUID was specified in PUC-680.
New requirement, to use name instead:
closes PUC-697

feat: On Enroll, baremetal local_link_info gets populated with name instead of UUID

---

python/neutron-understack/neutron_understack/trunk.py

Previously we changed the trunk_created and subports_added subscription event from AFTER_CREATE to PRECOMMIT_CREATE,  while that was not a problem for subports, it created a bug for trunk as DBEventPayload is constructed differently for trunk, hence we need this change.
code ref for trunk DBEventPayload on precommit:
https://github.com/openstack/neutron/blob/stable/2024.2/neutron/services/trunk/plugin.py#L263
As we see there, the "desired_state" is used instead of just "state".
If we call payload.latest_state, it will return desired if present, else it will return latest from state. code ref.
https://github.com/openstack/neutron-lib/blob/950f0f3a8a722da115c03f2abb756a732a3ec4c1/neutron_lib/callbacks/events.py#L142

fix: trunk_created payload parsing

---

.github/workflows/go-lint.yaml
go/deploy-cli/cmd/helmConfig/helmConfig.go
go/deploy-cli/cmd/other/other.go
go/deploy-cli/cmd/root.go
go/deploy-cli/helpers/kubeseal.go
go/deploy-cli/helpers/kustomization.go
go/deploy-cli/main.go

This PR enables golang linting as well as bunch of fixes for `deploy-cli`. The fixes for `dexop` are contained in #876

feat: enable Golangci linting

---

.github/renovate.json
.github/workflows/lint-workflow-templates.yaml

We've just pulled the latest argo workflows binary which has been working but their most recent release attempt ran up against Docker rate limits so it failed. The result is our CI is broken because the release binary is not available. To avoid this from happening in the future, pin the version but allow renovate to update it for us.

ci: pin argo workflows binary to not get broken by release process

---

components/ironic/values.yaml

Since we are still using iPXE with our UEFI boot, we need to have snponly.efi available to our servers to fetch. Utilize the ironic.conf config that causes the conductor to copy the file from the host OS, which is located at /usr/lib/ipxe/snponly.efi in our containers, to the path where it will serve it up from. fixes PUC-649.

fix(ironic): ensure that UEFI boot works by having snponly.efi

---

python/neutron-understack/neutron_understack/nautobot.py

Use the pynautobot API calls instead of making manual API calls in the neutron mechanism. While typing is a bit awkward and needs some casts currently, it will be better for long term maintainability to use the API library than writing our own calls everywhere. This can be seen by the ability to consistently catch errors and return them back to neutron which should eliminate a few 500 errors that users see without any context.

chore(neutron): replace manual API calls with pynautobot

---

components/openstack/mariadb-instance.yaml
scripts/gitops-secrets-gen.sh

We do not need this password so it can be generated by default.

chore(mariadb): auto-generate root password by default

---

docs/deploy-guide/deploy-repo.md
docs/deploy-guide/getting-started.md
docs/deploy-guide/gitops-install.md
docs/deploy-guide/management-cluster.md
docs/deploy-guide/welcome.md
mkdocs.yml

Add more details around the deployment repo and how to structure it.

docs: update more information about the deployment repo

---

python/understack-workflows/understack_workflows/ironic_node.py

Use HTTP with our UEFI boot. So we need to switch to http-ipxe over ipxe.

feat:PUC-314: set default boot-interface to http-ipxe

---

docs/design-guide/intro.md
docs/design-guide/neutron-networking.md
mkdocs.yml

Add an initial document that describes the behaviors and interactions of neutron with the system and where our code lives.

docs: add design information around neutron usage

---

apps/appsets/openstack.yaml
components/skyline/README.md
components/skyline/kustomization.yaml
components/skyline/skyline-mariadb-db.yaml
components/skyline/values.yaml
scripts/gitops-secrets-gen.sh

Adds the OpenStack Skyline dashboard to Understack. Skyline is a modern version of the OpenStack Horizon dashboard we already have available in Understack.

feat: Adds OpenStack Skyline dashboard to Understack

---

apps/appsets/appset-understack-infra.yaml
apps/appsets/appset-understack-operators.yaml
apps/appsets/understack.yaml

These finalizers will delete Applications which isn't what we want as we move things around for deployment changes.

chore: we are making deploy changes so remove the finalizers

---

docs/design-guide/neutron-networking.md

Add some details from OVN to the neutron network document to show how the data lines up.

docs: add details on OVN to the neutron net docs

---

docs/user-guide/openstack-image.md

Adds docs on how to build and add Talos Linux images to Understack.

docs: Adds notes on Talos Linux images

---

bootstrap/argocd/values.yaml

fix to bypass Kustomize security restriction that prevents from referencing files outside of the directory containing kustomization.yaml.
There are few places where we need this for example to include [ansible inventory](https://github.com/RSS-Engineering/undercloud-deploy/blob/5af4f74813fe4710d0251cd24f422da0cda527a4/bravo-uc-iad3-dev/manifests/openstack/kustomization.yaml#L12) as config map so that we can volume mount.

fix: allow outside dir files in kustomization.yaml

---

python/neutron-understack/neutron_understack/nautobot.py

fix: ucvni url typo in nautobot client

---

.github/renovate/understackContainerMatch.json

Update to include understack/ in the depName match. Adjust the currentVersion to only take things prefixed with v followed by numbers. Drop the versioningTemplate since docker tags are not semver but renovate should use the correct default.

fix: attempt to update understack container matching for renovate

---

.github/renovate/understackContainerMatch.json

Rather than treating each understack container separately in renovate, let's group them all together under the understack umbrella.

feat: further group understack containers together in updates

---

.github/workflows/trufflehog.yaml

Prior version does not behave correctly if the commit message includes a single quote as the shell does not escape the payload.
Example of a failure:
https://github.com/RSS-Engineering/undercloud-deploy/actions/runs/14983079151/job/42091474992

fix: change Trufflehog workflow to use Github script

---

python/neutron-understack/neutron_understack/neutron_understack_mech.py
python/neutron-understack/neutron_understack/tests/test_trunk.py
python/neutron-understack/neutron_understack/trunk.py
python/neutron-understack/neutron_understack/utils.py

Sometimes we have to define vlan segment statically in openstack, i.e for infra vlans and allocate_dynamic_segments does not check if there is statically defined segment, therefor this fix is needed to use those segments if they are present.
closes PUC-925

fix: check static network segments on bind

---

components/images-openstack.yaml
containers/ironic/Dockerfile.ironic
containers/ironic/patches/0001_use_update_pxe_enabled_conf.patch
containers/ironic/patches/series
workflows/argo-events/workflowtemplates/enroll-server.yaml

this fix also contains patch https://review.opendev.org/c/openstack/ironic/+/951716 for using update_pxe_enabled flag to enable/disable port updation while inspect. In our case we disable it which is done in [https://github.com/RSS-Engineering/undercloud-deploy/pull/350](https://github.com/RSS-Engineering/undercloud-deploy/pull/350)

feat: run inspection on enroll

---

components/images-openstack.yaml

There are two similar openvswitch images being build upstream by openstack: https://opendev.org/openstack/openstack-helm-images/src/branch/master/openvswitch
The ubuntu-jammy image we were using only has the openvswitch-switch package, but the dpdk image includes some additional packages and useful tools, such as iproute2 which contains a required tool `ip` used by openstack-helm init containers and scripts.

fix: use openvswitch dpdk image which contains needed packages

---

python/neutron-understack/neutron_understack/ironic.py
python/neutron-understack/neutron_understack/neutron_understack_mech.py
python/neutron-understack/neutron_understack/tests/conftest.py
python/neutron-understack/neutron_understack/trunk.py
python/neutron-understack/neutron_understack/utils.py

change ironic client to get port by local link info
This will help us when baremetal ports are in port group as currently we're looking to find a baremetal port by mac address, but in case of port groups, the mac will not be the physical mac but it will be assigned by neutron. We cannot use internal info either as during provisioning calls to our driver that info is not present yet. Instead we'll be using local link info as that is present.

fix: change ironic client to get port by local link info

---

components/images-openstack.yaml

In 45d55d30830 the chart was bumped but we needed to bump to a container with the user inside of it otherwise it fails to start up.
This fixes #1006 which needed a newer container.

fix(openstack): bump open vswitch container for 45d55d30830

---

apps/openstack/neutron.yaml

https://review.opendev.org/c/openstack/openstack-helm/+/949058 contained an invalid volumes spec for the neutron-ironic-agent preventing it from starting up. So revert back to before that landed. https://review.opendev.org/c/openstack/openstack-helm/+/952611 has been submitted to fix this.

fix(neutron): revert OpenStack Helm chart version

---

components/ironic/values.yaml
containers/dnsmasq/dnsmasq/dnsmasq.conf.j2

These paths are defaulted within /var/lib/openstack-helm and should remain that way to avoid cross filesystem operations.

fix(ironic): do not override OpenStack Helm default paths

---

components/ironic/values.yaml

When we have ilo-ipxe and ipxe interfaces enabled, they check that the boot files exist so we need the directory to be created so the files can be copied into place.

fix(ironic): ensure tftpboot path is created

---

operators/rook/values-cluster.yaml

This adds a storage class and ceph block pool that is not replicated anywhere. The data is stored only on the local machine. It will be used for applications that handle replication on the higher level (postgres, rabbitmq, galera, etc).

feat: rook - add ceph-block-single block pool

---

components/ironic/values.yaml
components/openstack-secrets.tpl.yaml
go/understackctl/cmd/other/openstack.go

All charts have the proper values and default them to keep them in sync except for the Ironic chart. We can drop this configuration in the deploy repos and just default it in Ironic until upstream fixes the issue.

chore: only set the tls secretName as needed

---

python/neutron-understack/neutron_understack/neutron_understack_mech.py
python/neutron-understack/neutron_understack/routers.py
python/neutron-understack/neutron_understack/tests/conftest.py
python/neutron-understack/neutron_understack/tests/test_routers.py

This code must be executed after Neutron's core validations but before the delete transaction is committed so we would still have enough information to perform full cleanup.
Prior version had a bug where user could accidentally delete the data related to a router's port (OVN router port, uplink neutron port, etc) while attempting to detach router's interface that was still in use for floating IP.
More details at https://rackspace.atlassian.net/browse/PUC-980
Closes PUC-890

fix: router iface removal: switch to PRECOMMIT_DELETE 

---

components/images-openstack.yaml
containers/cinder/Dockerfile

The other OpenStack Helm images have already switched to using quay.io as the source of images.

fix: switch Cinder and Placement to quay.io images

---

apps/appsets/appset-understack-global.yaml
apps/appsets/appset-understack-infra.yaml
apps/appsets/appset-understack-openstack.yaml
apps/appsets/appset-understack-operators.yaml
apps/appsets/appset-understack-site.yaml

I originally added this nested variable and referenced an upstream issue believing it was necessary but local testing showed this didn't work and in fact is not necessary so remove it.

fix(argocd): correct the git generator referencing the cluster

---

apps/appsets/appset-understack-global.yaml
apps/appsets/appset-understack-infra.yaml
apps/appsets/appset-understack-openstack.yaml
apps/appsets/appset-understack-operators.yaml
apps/appsets/appset-understack-site.yaml

Documented what all the sync options do. Enabled applying only the objects that are out of sync which will prevent certain things that are marked for re-creation from being run all the time like the OpenStack Helm db-sync and keystone user/endpoint jobs. Removed every OpenStack component from fighting over owning the openstack namespace since it's created and owned by the shared resources anyway.

feat(argocd): sync only out of sync objects and don't manipulate the openstack namespace everywhere

---

apps/aio-app-of-apps.yaml
apps/app-of-apps.yaml
apps/appsets/appset-understack-global.yaml
apps/appsets/appset-understack-infra.yaml
apps/appsets/appset-understack-openstack.yaml
apps/appsets/appset-understack-operators.yaml
apps/appsets/appset-understack-site.yaml
apps/appsets/argocd/appset-argocd.yaml

This is a followup to https://github.com/pvceng-sre/argocd-infra/pull/65
The aim is to allow operators to temporarily pause the automated synchronization for particular apps to facilitate debugging, migrations and similar.
ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#allow-temporarily-toggling-auto-sync

feat: argocd: allow operators to control syncPolicy

---

components/nova/values.yaml

Increases the default quota due to users hitting ram quota limits.

fix(quotas): Increases default ram quota

---

components/nova/values.yaml

```
2025-07-09 20:26:53.557 7 CRITICAL nova [-] Unhandled error: oslo_config.cfg.ConfigFileValueError: Value for option ram from LocationInfo(location=<Locations.user: (4, True)>, detail='/etc/nova/nova.conf') is not valid: invalid literal for int() with base 10: '1.024e+06'
2025-07-09 20:26:53.557 7 ERROR nova Traceback (most recent call last):
2025-07-09 20:26:53.557 7 ERROR nova   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_config/cfg.py", line 2933, in _do_get
2025-07-09 20:26:53.557 7 ERROR nova     return (convert(val), alt_loc)
2025-07-09 20:26:53.557 7 ERROR nova   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_config/cfg.py", line 2902, in convert
2025-07-09 20:26:53.557 7 ERROR nova     return self._convert_value(
2025-07-09 20:26:53.557 7 ERROR nova …
```

fix(nova): make ram quota a string so that openstack-helm doesn't convert it to scientific notation

---

apps/appsets/appset-understack-global.yaml
apps/appsets/appset-understack-infra.yaml
apps/appsets/appset-understack-openstack.yaml
apps/appsets/appset-understack-operators.yaml
apps/appsets/appset-understack-site.yaml

On sync we should prune removed resources from the application by default. Document the syncPolicy and be explicit able the enabled flag.
ref: PUC-1021

feat(argocd): re-enable pruning of application resources

---

.typos.toml
apps/openstack/cinder.yaml
components/cinder/README.md
components/cinder/cinder-mariadb-db.yaml
components/cinder/cinder-rabbitmq-queue.yaml
components/cinder/kustomization.yaml
components/cinder/values.yaml
components/openstack-secrets.tpl.yaml
scripts/gitops-secrets-gen.sh

This adds a deployment of OpenStack Cinder via OpenStack Helm.

feat: add deployment of OpenStack Cinder

---

.github/renovate/understackContainerMatch.json

Update the renovate regex rule to handle digest pinning as per https://github.com/renovatebot/renovate/issues/10993

fix: renovate needs to update to handle digest pinning

---

python/understack-workflows/tests/test_sync_interfaces.py
python/understack-workflows/understack_workflows/sync_interfaces.py

Standardize the ironic port names to be the node-name:port-name since they have to be unique in Ironic but we want to include the BMC name to make it clear to folks which NIC is which.
ref: PUC-1037

feat: make ironic port names node-name:port-name as a standard

---

components/cinder/values.yaml
components/skyline/values.yaml

Fixed missing job annotations for skyline and fixed incorrectly included jobs for cinder.

fix: correct missing job annotations or incorrectly included jobs

---

.github/renovate/understackContainerMatch.json

This should match ALL containers that are referenced in the images-openstack.yaml file and not just those in this repo's container registry.
ref: PUC-1004

fix(renovate): update rule for keeping containers current

---

.github/renovate/understackContainerMatch.json

The OpenStack Helm containers have an _ in the tag name so we need to add that to the pattern. follow on to #1106

fix(renovate): allow _ in container tag names

---

.github/renovate/understackContainerMatch.json

This should hopefully simplify the whole match and just support docker container image references in general. Looks like some of the prior things I had been doing are no longer required but are still showing up in searches and results on renovate's site but its all been upstreamed.

fix(renovate): simplify the container match rule

---

python/cinder-understack/cinder_understack/dynamic_netapp_driver.py

https://rackspace.atlassian.net/browse/PUC-1104
This update enhances the NetApp dynamic driver to support real FlexVol discovery and accurate pool capacity reporting, enabling more reliable volume scheduling and placement in OpenStack Cinder.
**Real FlexVol Discovery** -Retrieves actual FlexVol names and capacity details directly from the NetApp backend using the REST API.
**Pool Name Extraction** -Maps FlexVols to Cinder pool names correctly, ensuring volumes are routed to the right pool selected by the scheduler.
**Enhanced Logging** -Adds detailed logs during pool discovery and update operations to aid in debugging and traceability.
**Scheduler Integration**-Exposes real-time capacity and pool stats to the scheduler for accurate volume placement decisions.
**Namespace** - map …

feat: Add Proper Pool Discovery and FlexVol Integration

---

components/cinder/cinder-volume-netapp.yaml

This change points to custom dynamic NetApp driver class located in the /python/cinder-understack/cinder_understack/dynamic_netapp_driver.py module. The path follows Python's module naming convention where the file path translates to the module path cinder_understack.dynamic_netapp_driver.NetappCinderDynamicDriver.

feat: Updated new driver for netapp dynamic svm

---

python/understack-workflows/tests/test_sync_keystone.py
python/understack-workflows/understack_workflows/main/sync_keystone.py

fix for [PUC-867](https://rackspace.atlassian.net/browse/PUC-867)
[PUC-867]: https://rackspace.atlassian.net/browse/PUC-867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: unmap Nautobot devices from tenant during keystone project deletion

---

components/nautobot/values.yaml

This sets Nautobot to use the same limits for all our environments. For celery, I'm also limiting concurrency. We don't run a lot of jobs currently so we maybe need to tune that more in the future.
Concurrency defaults to number of CPUs in the system: https://docs.nautobot.com/projects/core/en/stable/user-guide/administration/guides/celery-queues/
A nautobot issue related to OOM issues: https://github.com/nautobot/helm-charts/issues/433 says "If your concurrency is set too high for the resource requests and limits then you'll have a large amount of memory taken by all the worker processes."

fix(nautobot): Performance tuning for nautobot

---

components/nautobot/cloudnative-postgres-nautobot.yaml

With current setup we are running into situations where postgres instances are not spread evenly across the nodes:
```
❯ kubectl cnpg status nautobot-cluster -n nautobot
...
Instances status
Name                Current LSN   Replication role  Status  QoS         Manager Version  Node
----                -----------   ----------------  ------  ---         ---------------  ----
nautobot-cluster-4  16C/C4001338  Primary           OK      BestEffort  1.26.0           1327175-hp3
nautobot-cluster-5  16C/C4001338  Standby (async)   OK      BestEffort  1.26.0           1327174-hp2
nautobot-cluster-6  16C/C4001338  Standby (async)   OK      BestEffort  1.26.0           1327174-hp2
```
Adding the rules here will ensure that they are distributed across multiple servers.

fix(postgres): specify antiaffinity rules

---

containers/ironic/patches/0002_skip_reboot_firmware_update.patch
containers/ironic/patches/series

ironic upstream patch [Skip initial reboot to IPA when updating firmware out-of-band](https://review.opendev.org/c/openstack/ironic/+/954311)

feat: upstream patch skip initial reboot to IPA when updating firmware out-of-band

---

.pre-commit-config.yaml
python/understack-workflows/pyproject.toml
python/understack-workflows/tests/test_keystone_project.py
python/understack-workflows/understack_workflows/oslo_event/keystone_project.py
scripts/delete_volumes_and_svms_netapp.py
workflows/argo-events/workflowtemplates/openstack-oslo-event.yaml
workflows/openstack/sensors/sensor-keystone-oslo-event.yaml

When the Keystone project is created and it has `UNDERSTACK_SVM` tag, it will now:
- create the actual SVM on the NetAPP
- convert received Keystone project ID to a version with dashes
- if the NetApp creation was successful, it will kickoff the `storage_on_svm_create.yml` playbook

feat: Trigger Ansible on SVM creation

---

python/understack-workflows/tests/test_sync_keystone.py
python/understack-workflows/understack_workflows/main/sync_keystone.py

We needed to create this network on behalf of the tenant because it
required admin privs to make an "external" network.   We can now achieve
the same effect using a normal network that a tenant can create for
themselves.
The user will create a network, subnet and router.  This has the same end result, and therefore we are no longer going to support the OUTSIDE network.
The intention is to proactively delete all existing OUTSIDE networks, so I have gone ahead and removed the cleanup code from here.

chore: sync_keystone: Stop managing OUTSIDE networks for tenants

---

python/cinder-understack/cinder_understack/dynamic_netapp_driver.py
python/cinder-understack/cinder_understack/tests/test_dynamic_netapp_driver.py

The clean up and error handling paths were not actually correct and caused crashes and further errors which prevented the driver from starting up correctly if it encountered an error or to fail to continue to run if any SVM encountered an error.

fix(cinder-understack): correct cleanup and error handling to not be the problem

---

workflows/argo-events/sensors/alertmanager-webhook-sensor.yaml
workflows/openstack/sensors/sensor-ironic-node-port.yaml
workflows/openstack/sensors/sensor-ironic-node-update.yaml
workflows/openstack/sensors/sensor-ironic-reclean.yaml
workflows/openstack/sensors/sensor-keystone-event-project.yaml
workflows/openstack/sensors/sensor-neutron-event-network-segment-range.yaml

Change the Argo Events Sensors to using the k8s object creation trigger instead of the argoWorkflow trigger which will require less permissions and to better specify the service accounts.
ref: PUC-1125

chore(workflows): convert to k8s object triggers

---

python/cinder-understack/cinder_understack/dynamic_netapp_driver.py

The follow error can be seen in the Cinder logs because the SVM name has already been stripped from the pool name in the volume host due to one call calling another driver call. To handle this we will detect this case and detect the SVM name from the project ID and not fail.
```
ERROR cinder_understack.dynamic_netapp_driver [req-f6486c4b-bae2-4c4c-8a33-5ecdca412712 req-4b7cca6a-4421-4f8e-bfec-8858176fb723 c3fd23244abd42631651813496e0ee22bd2377690c1d9b0e7851804e0497775f 6c2fb34446bf4b35b4f1512e51f2303d - - - -] No such SVM vol_6c2fb34446bf4b35b4f1512e51f2303d instantiated
```
The second fix here is a workaround for the fact that nova ironic sets the key "initiator" with the necessary data when the cinder NetApp driver expects the key "nqn" to store the data. This copies "initator" over to …

fix(cinder-understack): handle SVM name stripped in pool name and bad values passed from nova

---

components/dex/values.yaml
docs/deploy-guide/config-dex.md
mkdocs.yml

There have been some fixes upstream which made it into v2.44.0 to be able to support the device authorization flow. Unfortunately we will need to add an ingress rule to make it work so document the change users will need to do.

feat(dex): bump version to support device authorization flow

---

.github/renovate.json

Instead of a PR per Argo Workflow container, create one PR for all of them together to bump the version as one.

chore: ensure Argo Workflows upgrade as one PR

---

components/openstack/templates/mariadb-instance.yaml.tpl
components/openstack/values.schema.json
docs/deploy-guide/config-openstack.md
docs/schema/component-openstack.schema.json
mkdocs.yml

Created a schema for the current chart and validated samples we have against it. Updated a few fields from JSON to YAML to make it consistent and let my validation test pass. Symlink the schema so that it is able to be fetched. Added documentation around how to configure this part of a deployment.

chore(openstack): create schema and document configuration

---

python/understack-tests/README.md
python/understack-tests/build_a_single_server_with_network.yaml

Add ability to specify a different flavor in the rally build test scenario.

feat: Adds ability to specify flavor for build tests

---

workflows/argo-events/kustomization.yaml
workflows/argo-events/workflowtemplates/ansible-run.yaml
workflows/openstack/sensors/sensor-ironic-oslo-event.yaml
workflows/openstack/sensors/sensor-keystone-oslo-event.yaml

This PR changes the storage related Argo Workflows and Sensors to stop using hardcoded `env` variables and switches to [generic inventory added in undercloud-rackspace#533](https://github.com/RSS-Engineering/undercloud-rackspace/pull/533). 
The environment variables are now dynamically set by reading the `UNDERSTACK_ENV` variable that is injected through [`cluster-metadata` ConfigMap](https://github.com/RSS-Engineering/undercloud-deploy/pull/691)
Related:
- https://github.com/RSS-Engineering/undercloud-deploy/pull/691
- https://github.com/RSS-Engineering/undercloud-rackspace/pull/533
- https://rackspace.atlassian.net/browse/PUC-1170
Closes https://rackspace.atlassian.net/browse/PUC-1200

feat: Storage support multiple environments

---

components/openstack-secrets.tpl.yaml

We do not need this templated in anymore since we are using ESO to configure these secrets and no longer need the OpenStack Helm charts to template them in.

chore: remove unused password refs in the openstack helm values file

---

apps/operators/external-dns.yaml

This is updating chart version for external-dns full change log for external-dns can be found here 
https://github.com/rackerlabs/external-dns-rackspace-webhook/releases/tag/v0.0.2

fix: external-dns chart version update

---

.github/renovate.json

Our Python version comes from the OS container we are shipping with. There's multiple Python versions involved so let's skip this rule entirely for now and create something later to check the appropriate versions.

chore(renovate): skip Python version bumps

---

components/nova/values.yaml
docs/operator-guide/openstack-ironic.md

Enables nova scheduler filters and adds docs on using them

feat(nova): Enables nova scheduler filters and adds docs on using them

---

python/understack-tests/build_a_single_server_with_network.yaml

The original issue necessitating the use of the `users_custom` plugin was that we had to wait for the project creation sync from keystone to nautobot to complete. This process has been refactored and we no longer need to wait for the sync.

fix(rally): We no longer need to use a custom user plugin

---

docs/operator-guide/openstack-ironic.md

Added some documentation around manual node enrollment into the system.

docs: add operator info about manual node enrollment
